/* B5 v0.9.16a — in-contract signature capture and rendering */
(function(){
const roles={lessee:{sig:'lessee_signature',name:'lessee_signed_name',at:'lessee_signed_at',label:'Lessee Signature'},management:{sig:'management_signature',name:'management_signed_name',at:'management_signed_at',label:'Management Signature'}};
const escHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v){if(!v)return'';try{return new Intl.DateTimeFormat('en-AU',{dateStyle:'medium',timeStyle:'short',timeZone:'Australia/Sydney'}).format(new Date(v))+' Sydney';}catch{return new Date(v).toLocaleString();}}
function verificationId(c){return 'ASR-'+String(c?.id||'').replaceAll('-','').slice(0,8).toUpperCase();}
function panel(role,label){const c=window.contractCtx?.contract||{},r=roles[role],sig=c[r.sig],name=c[r.name],at=c[r.at];return `<div class="signature-box b5-signature-panel" data-b5-signature="${role}"><label>${label||r.label}</label><div class="b5-signature-surface" data-sign-role="${role}">${sig?`<img src="${sig}" alt="${escHtml(r.label)}">`:`<span class="b5-signature-awaiting">Awaiting signature</span>`}</div>${sig?`<div class="b5-signature-meta"><strong>${escHtml(name||'Signed')}</strong><br>Signed ${escHtml(fmt(at))}</div>`:''}<div class="b5-signature-actions"><button type="button" class="primary" data-capture-sign="${role}">${sig?'Replace':'Sign'}</button>${sig?`<button type="button" data-clear-sign="${role}">Clear</button>`:''}</div></div>`;}
function replaceBox(id,role,label){const old=document.getElementById(id);if(!old)return;const box=old.closest('.signature-box');if(!box)return;box.outerHTML=panel(role,label);}
function render(){const c=window.contractCtx?.contract;if(!c)return;replaceBox('termsLessee','lessee','Second Party / Lessee · Full Name & Signature');replaceBox('termsLessor','management','First Party / All Season Car Rental · Signature / Seal');replaceBox('receiverSig','lessee',"Car's Receiver / الاسم والتوقيع");replaceBox('deliverSig','management',"Car's Deliver / الاسم والتوقيع");document.querySelectorAll('.b5-signature-audit').forEach(x=>x.remove());const signed=c.lessee_signed_at||c.management_signed_at;if(signed){const a=document.createElement('div');a.className='b5-signature-audit';a.textContent=`Digitally signed and recorded by All Season Car Rental · Contract ${c.contract_number||''} · ${fmt(signed)} · Verification ID: ${verificationId(c)}`;document.getElementById('page2')?.appendChild(a);}bind();}
function bind(){document.querySelectorAll('[data-capture-sign]').forEach(b=>b.onclick=()=>capture(b.dataset.captureSign));document.querySelectorAll('[data-clear-sign]').forEach(b=>b.onclick=()=>clearSig(b.dataset.clearSign));}
async function clearSig(role){if(!confirm('Clear this stored signature?'))return;const r=roles[role],patch={[r.sig]:null,[r.name]:null,[r.at]:null,updated_at:new Date().toISOString()};const {data,error}=await window.db.from('contracts').update(patch).eq('id',contractCtx.contract.id).select().single();if(error)return alert(error.message);contractCtx.contract=data;render();}
function capture(role){const r=roles[role],c=contractCtx.contract;if(!c)return;const dlg=document.createElement('div');dlg.className='b5-signature-dialog';dlg.innerHTML=`<div class="b5-signature-card"><h3>${escHtml(r.label)}</h3><div class="small">Sign with finger, stylus or mouse.</div><input id="b5SignerName" placeholder="Full name" value="${escHtml(c[r.name]||((role==='lessee'&&contractCtx.customer)?[contractCtx.customer.first_name,contractCtx.customer.family_name].filter(Boolean).join(' '):(contractCtx.user?.email||'')))}"><canvas class="b5-signature-canvas" id="b5SigCanvas"></canvas><div class="b5-signature-dialog-actions"><button type="button" id="b5SigCancel">Cancel</button><button type="button" id="b5SigClear">Clear</button><button type="button" class="btn-primary" id="b5SigSave">Save Signature</button></div></div>`;document.body.appendChild(dlg);const cv=dlg.querySelector('canvas'),ctx=cv.getContext('2d'),rect=cv.getBoundingClientRect();cv.width=Math.max(700,Math.floor(rect.width*2));cv.height=380;ctx.lineWidth=4;ctx.lineCap='round';ctx.strokeStyle='#102236';let down=false,dirty=false;const p=e=>{const q=cv.getBoundingClientRect();return{x:(e.clientX-q.left)*cv.width/q.width,y:(e.clientY-q.top)*cv.height/q.height}};cv.onpointerdown=e=>{e.preventDefault();down=dirty=true;cv.setPointerCapture?.(e.pointerId);const q=p(e);ctx.beginPath();ctx.moveTo(q.x,q.y)};cv.onpointermove=e=>{if(!down)return;e.preventDefault();const q=p(e);ctx.lineTo(q.x,q.y);ctx.stroke()};cv.onpointerup=cv.onpointercancel=()=>down=false;dlg.querySelector('#b5SigCancel').onclick=()=>dlg.remove();dlg.querySelector('#b5SigClear').onclick=()=>{ctx.clearRect(0,0,cv.width,cv.height);dirty=false};dlg.querySelector('#b5SigSave').onclick=async()=>{const name=dlg.querySelector('#b5SignerName').value.trim();if(!name)return alert('Enter the signer’s full name.');if(!dirty)return alert('Please add a signature.');const now=new Date().toISOString(),patch={[r.sig]:cv.toDataURL('image/png'),[r.name]:name,[r.at]:now,updated_at:now};const {data,error}=await window.db.from('contracts').update(patch).eq('id',c.id).select().single();if(error)return alert(error.message);contractCtx.contract=data;dlg.remove();render();};}
window.b5RenderContractSignatures=render;
let tries=0,last='';const timer=setInterval(()=>{tries++;const c=window.contractCtx?.contract,key=c?`${c.id}:${c.lessee_signed_at||''}:${c.management_signed_at||''}`:'';if(c&&key!==last){last=key;render();}if(tries>120)clearInterval(timer);},250);
})();