/* B5 v0.8.6 — role + individual user permissions */
const B5_PERMISSION_DEFS=[
 ["dashboard","General","Dashboard"],["today","General","Today"],["availability","General","Availability"],["calendar","General","Calendar"],
 ["rentals.view","Rentals & Contracts","View Rentals"],["rentals.create","Rentals & Contracts","Create Rentals"],["rentals.edit","Rentals & Contracts","Edit / Extend / Change Vehicle"],["rentals.return","Rentals & Contracts","Return Vehicles"],["contracts.view","Rentals & Contracts","View Contracts"],["contracts.edit","Rentals & Contracts","Create / Edit Contracts"],["contracts.finalise","Rentals & Contracts","Finalise Contracts"],
 ["fleet.view","Fleet & Customers","View Fleet"],["fleet.edit","Fleet & Customers","Add / Edit Vehicles"],["customers.view","Fleet & Customers","View Customers"],["customers.edit","Fleet & Customers","Add / Edit Customers"],["maintenance","Fleet & Customers","Maintenance"],
 ["payments","Money","Record Payments"],["expenses","Money","Expenses"],["reports","Money","Operational Reports"],["financial_reports","Money","Financial Reports"],["promotions","Money","Promo Codes"],
 ["suppliers","Administration","Suppliers"],["locations","Administration","Locations & Fees"],["manager","Administration","Manager Mode / Audit Log"],["users.manage","Administration","Manage Users & Permissions"],["settings","Administration","System Settings"]
];
const B5_ROLE_DEFAULTS={
 manager:Object.fromEntries(B5_PERMISSION_DEFS.map(([k])=>[k,true])),
 office:{dashboard:true,today:true,availability:true,calendar:true,"rentals.view":true,"rentals.create":true,"rentals.edit":true,"rentals.return":true,"contracts.view":true,"contracts.edit":true,"contracts.finalise":false,"fleet.view":true,"fleet.edit":false,"customers.view":true,"customers.edit":true,maintenance:false,payments:true,expenses:false,reports:true,financial_reports:false,promotions:false,suppliers:true,locations:true,manager:false,"users.manage":false,settings:false},
 accounts:{dashboard:true,today:true,availability:false,calendar:false,"rentals.view":true,"rentals.create":false,"rentals.edit":false,"rentals.return":false,"contracts.view":true,"contracts.edit":false,"contracts.finalise":false,"fleet.view":true,"fleet.edit":false,"customers.view":true,"customers.edit":false,maintenance:false,payments:true,expenses:true,reports:true,financial_reports:true,promotions:false,suppliers:true,locations:false,manager:false,"users.manage":false,settings:false},
 operations:{dashboard:true,today:true,availability:true,calendar:true,"rentals.view":true,"rentals.create":false,"rentals.edit":false,"rentals.return":true,"contracts.view":true,"contracts.edit":true,"contracts.finalise":false,"fleet.view":true,"fleet.edit":false,"customers.view":true,"customers.edit":false,maintenance:true,payments:false,expenses:false,reports:false,financial_reports:false,promotions:false,suppliers:false,locations:false,manager:false,"users.manage":false,settings:false},
 readonly:{dashboard:true,today:true,availability:true,calendar:true,"rentals.view":true,"rentals.create":false,"rentals.edit":false,"rentals.return":false,"contracts.view":true,"contracts.edit":false,"contracts.finalise":false,"fleet.view":true,"fleet.edit":false,"customers.view":true,"customers.edit":false,maintenance:false,payments:false,expenses:false,reports:false,financial_reports:false,promotions:false,suppliers:false,locations:false,manager:false,"users.manage":false,settings:false}
};
Object.assign(state,{permissionProfiles:{},permissionEditorUser:null});
function permissionRole(p){return p?.permission_role||((p?.role||'').toLowerCase()==='manager'?'manager':'office');}
function permissionMap(p){return {...(B5_ROLE_DEFAULTS[permissionRole(p)]||B5_ROLE_DEFAULTS.office),...(p?.permissions||{})};}
function can(key,p=state.userProfile){if(isManager()&&!(p?.permissions&&Object.keys(p.permissions).length))return true;return permissionMap(p)[key]===true;}
function pagePermission(page){return ({dashboard:'dashboard',today:'today',availability:'availability',rentals:'rentals.view',calendar:'calendar',fleet:'fleet.view',customers:'customers.view',suppliers:'suppliers',locations:'locations',expenses:'expenses',reports:'reports',settings:'settings',manager:'manager'})[page]||'dashboard';}
function applyPermissionNavigation(){document.querySelectorAll('.nav-btn[data-page]').forEach(b=>{b.hidden=!can(pagePermission(b.dataset.page));});const m=document.getElementById('managerTopBtn');if(m)m.hidden=!can('manager');const q=document.getElementById('quickRental');if(q)q.hidden=!can('rentals.create');const a=document.getElementById('quickAvailability');if(a)a.hidden=!can('availability');}
function permissionProfileForEmail(email){return state.staffProfiles.find(x=>(x.email||'')===email)||null;}
function roleLabel(r){return ({manager:'Manager / Admin',office:'Office Staff',accounts:'Accounts',operations:'Operations / Driver',readonly:'Read Only'})[r]||r;}
function permissionEditorHtml(p){const role=permissionRole(p),map=permissionMap(p);const groups=[...new Set(B5_PERMISSION_DEFS.map(x=>x[1]))];return `<div class="permission-profile"><div class="permission-user-head"><div><h3>${esc(p.display_name||p.email||'User')}</h3><div class="vehicle-meta">${esc(p.email||'')} · ${p.active?'Active':'Inactive'}</div></div><span class="badge ${role==='manager'?'role-manager':'role-staff'}">${esc(roleLabel(role))}</span></div><div class="permission-role-row"><div class="field"><label>Base Role</label><select id="permissionRole">${Object.keys(B5_ROLE_DEFAULTS).map(r=>`<option value="${r}" ${r===role?'selected':''}>${esc(roleLabel(r))}</option>`).join('')}</select></div><div class="permission-note">Choose a sensible starting role, then customise individual access below.</div></div><div class="permission-groups">${groups.map(g=>`<div class="permission-group"><h4>${esc(g)}</h4>${B5_PERMISSION_DEFS.filter(x=>x[1]===g).map(([k,,label])=>`<div class="permission-item"><span>${esc(label)}</span><label class="permission-switch"><input type="checkbox" data-permission="${esc(k)}" ${map[k]?'checked':''}><i></i></label></div>`).join('')}</div>`).join('')}</div><div class="permission-actions"><button type="button" class="btn btn-secondary" id="resetRolePermissions">Reset to Role Defaults</button><button type="button" class="btn btn-primary" id="saveUserPermissions">Save Access</button></div><div class="permission-note">Permission changes are recorded in the audit log. Notification permissions can be added to this same profile later.</div></div>`;}
function openPermissionProfile(email){if(!can('users.manage'))return alert('You do not have permission to manage users.');const p=permissionProfileForEmail(email);if(!p)return;state.permissionEditorUser=email;document.getElementById('profileBody').innerHTML=permissionEditorHtml(p);const title=document.querySelector('#profileModal .modal-head h3');const sub=document.querySelector('#profileModal .vehicle-meta');if(title)title.textContent='User Access';if(sub)sub.textContent='Role and individual permissions';document.getElementById('profileModal').showModal();bindPermissionEditor();}
function bindPermissionEditor(){const p=permissionProfileForEmail(state.permissionEditorUser);if(!p)return;document.getElementById('permissionRole')?.addEventListener('change',e=>{const defs=B5_ROLE_DEFAULTS[e.target.value]||{};document.querySelectorAll('[data-permission]').forEach(x=>x.checked=!!defs[x.dataset.permission]);});document.getElementById('resetRolePermissions')?.addEventListener('click',()=>{const r=document.getElementById('permissionRole').value,defs=B5_ROLE_DEFAULTS[r]||{};document.querySelectorAll('[data-permission]').forEach(x=>x.checked=!!defs[x.dataset.permission]);});document.getElementById('saveUserPermissions')?.addEventListener('click',saveUserPermissions);}
async function saveUserPermissions(){const p=permissionProfileForEmail(state.permissionEditorUser);if(!p)return;const role=document.getElementById('permissionRole').value;const permissions={};document.querySelectorAll('[data-permission]').forEach(x=>permissions[x.dataset.permission]=x.checked);if((p.email||'')===(state.userProfile?.email||'')&&!permissions['users.manage']&&!confirm('This removes your own User Management permission. Continue?'))return;const payload={permission_role:role,permissions};const {data,error}=await window.db.from('staff_profiles').update(payload).eq('id',p.id).select().single();if(error){alert('The permissions database fields are not available yet. The v0.8.6 database migration needs to be applied before permissions can be saved.');return;}Object.assign(p,data);await logAudit('permissions_updated','staff_profile',p.id,{user:p.email,permission_role:role,permissions});document.getElementById('profileModal').close();render();alert('User access updated.');}
const _render086=render;render=function(){if(state.userProfile&&!can(pagePermission(state.page))){const allowed=['dashboard','today','availability','rentals','calendar','fleet','customers'].find(p=>can(pagePermission(p)));state.page=allowed||'dashboard';}_render086();applyPermissionNavigation();};
const _bindPageEvents086=bindPageEvents;bindPageEvents=function(){_bindPageEvents086();document.querySelectorAll('.manager-user-row').forEach(row=>{row.onclick=e=>{e.preventDefault();e.stopPropagation();openPermissionProfile(row.dataset.userEmail||'');};});if(document.getElementById('newCustomerBtn')&&!can('customers.edit'))document.getElementById('newCustomerBtn').hidden=true;if(document.getElementById('newVehicleBtn')&&!can('fleet.edit'))document.getElementById('newVehicleBtn').hidden=true;if(document.getElementById('newRentalBtn')&&!can('rentals.create'))document.getElementById('newRentalBtn').hidden=true;document.querySelectorAll('[data-payment]').forEach(x=>{if(!can('payments'))x.hidden=true;});document.querySelectorAll('[data-return]').forEach(x=>{if(!can('rentals.return'))x.hidden=true;});document.querySelectorAll('[data-extend],[data-swap]').forEach(x=>{if(!can('rentals.edit'))x.hidden=true;});};
const _go086=go;go=function(page){if(!can(pagePermission(page))){alert('You do not have access to this area.');return;}return _go086(page);};
