/* B5 v0.8.7 — PWA push notifications */
const B5_NOTIFICATION_TYPES=[['pickup','Pickup reminders'],['return','Return reminders'],['overdue','Overdue rentals'],['maintenance','Maintenance reminders']];
function b64ToUint8(s){const pad='='.repeat((4-s.length%4)%4),b=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b);return Uint8Array.from([...r].map(c=>c.charCodeAt(0)));}
async function pushReg(){if(!('serviceWorker'in navigator))throw new Error('Push notifications are not supported on this browser.');await navigator.serviceWorker.register('./sw.js?v=0.8.7',{scope:'./'});return navigator.serviceWorker.ready;}
async function currentPush(){try{return await (await pushReg()).pushManager.getSubscription();}catch{return null;}}
async function enablePush(){if(!('Notification'in window)||!('PushManager'in window))return alert('This device/browser does not support web push notifications.');if(await Notification.requestPermission()!=='granted')return alert('Notifications were not enabled.');const reg=await pushReg();const {data:s,error}=await window.db.from('app_public_settings').select('value').eq('key','vapid_public_key').single();if(error)throw error;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8(s.value)});const raw=sub.toJSON(),{data:{session}}=await window.db.auth.getSession();if(!session)throw new Error('Please sign in again.');const row={user_id:session.user.id,endpoint:raw.endpoint,p256dh:raw.keys.p256dh,auth:raw.keys.auth,user_agent:navigator.userAgent,device_label:navigator.userAgentData?.platform||navigator.platform||'Device',active:true,updated_at:new Date().toISOString()};const {error}=await window.db.from('push_subscriptions').upsert(row,{onConflict:'endpoint'});if(error)throw error;await logAudit('push_enabled','staff_profile',session.user.id,{device:row.device_label});alert('Notifications enabled on this device.');openUserProfile();}
async function disablePush(){const sub=await currentPush();if(sub){await window.db.from('push_subscriptions').update({active:false,updated_at:new Date().toISOString()}).eq('endpoint',sub.endpoint);await sub.unsubscribe();}alert('Notifications disabled on this device.');openUserProfile();}
async function testPush(){const {data:{session}}=await window.db.auth.getSession();if(!session)return;const {data,error}=await window.db.functions.invoke('b5-push-notifications',{body:{action:'test'}});if(error)return alert('Test notification failed.');if(!data?.sent)alert('No active notification subscription was found.');}
async function savePushPrefs(){const prefs={};document.querySelectorAll('[data-notification-pref]').forEach(x=>prefs[x.dataset.notificationPref]=x.checked);const {data:{session}}=await window.db.auth.getSession();if(!session)return;const {error}=await window.db.from('staff_profiles').update({notification_preferences:prefs}).eq('user_id',session.user.id);if(error)return alert('Unable to save notification preferences.');state.userProfile.notification_preferences=prefs;await logAudit('notification_preferences_updated','staff_profile',session.user.id,prefs);alert('Notification preferences saved.');}
async function pushSettingsHtml(){const supported='serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window,sub=supported?await currentPush():null,prefs=state.userProfile?.notification_preferences||{pickup:true,return:true,overdue:true,maintenance:true};return `<div class="notification-card" id="notificationSettingsCard"><div class="notification-card-head"><div><strong>Push Notifications</strong><div class="vehicle-meta">Receive B5 alerts even when the app is not open.</div></div><span class="notification-status ${sub?'on':''}">${sub?'Enabled on this device':supported?'Not enabled':'Not supported'}</span></div><div class="notification-options">${B5_NOTIFICATION_TYPES.map(([k,l])=>`<label class="notification-option"><span>${esc(l)}</span><input type="checkbox" data-notification-pref="${k}" ${prefs[k]!==false?'checked':''}></label>`).join('')}</div><div class="notification-actions">${sub?'<button class="btn btn-secondary" type="button" id="disablePushBtn">Disable on Device</button><button class="btn btn-secondary" type="button" id="testPushBtn">Send Test</button>':'<button class="btn btn-primary" type="button" id="enablePushBtn" '+(!supported?'disabled':'')+'>Enable on This Device</button>'}<button class="btn btn-primary" type="button" id="savePushPrefs">Save Preferences</button></div><div class="notification-help">B5 checks every 15 minutes for pickups and returns due within 2 hours, overdue rentals and maintenance thresholds at 5,000 / 3,000 / 1,000 km.</div></div>`;}
function bindPushButtons(){document.getElementById('enablePushBtn')?.addEventListener('click',()=>enablePush().catch(e=>alert(e.message||'Unable to enable notifications.')));document.getElementById('disablePushBtn')?.addEventListener('click',()=>disablePush().catch(e=>alert(e.message||'Unable to disable notifications.')));document.getElementById('testPushBtn')?.addEventListener('click',testPush);document.getElementById('savePushPrefs')?.addEventListener('click',savePushPrefs);}
const _openUserProfile087=openUserProfile;openUserProfile=async function(){_openUserProfile087();const body=document.getElementById('profileBody');if(!body)return;body.insertAdjacentHTML('beforeend',await pushSettingsHtml());bindPushButtons();};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=0.8.7',{scope:'./'}).catch(console.warn));
