/* B5 v0.8.92 — compact labelled customer profiles + promo generator constraint fix */
(function(){
  function currentRentalForCustomer(id){return state.rentals.filter(r=>String(r.customer_id)===String(id)&&['Active','Confirmed','Reserved'].includes(r.status)).sort((a,b)=>new Date(a.start)-new Date(b.start))[0]||null;}
  function openRentalNow(uuid){if(typeof openRentalDetails==='function')openRentalDetails(uuid);else if(typeof openRentalDirect==='function')openRentalDirect(uuid);else openRentalInRentals(uuid);}

  openCustomerProfile=function(id){
    const c=customerById(id);if(!c)return;
    const rentals=state.rentals.filter(r=>String(r.customer_id)===String(id)).sort((a,b)=>new Date(b.start)-new Date(a.start));
    const active=currentRentalForCustomer(id),outstanding=customerOutstanding(id);
    const history=rentals.length?`<div class="customer-history-list">${rentals.map(r=>{const v=vehicleById(r.vehicle_id),bal=Math.max(0,rentalFinancials(r.uuid).balance);return `<button type="button" class="customer-history-card" data-customer-rental="${esc(r.uuid)}"><div><span>Rental</span><strong>#${esc(r.id)}</strong></div><div><span>Status</span><strong>${esc(r.status)}</strong></div><div class="wide"><span>Vehicle</span><strong>${v?`${esc(v.make)} ${esc(v.model)} · ${esc(v.plate||'No plate')}`:'Unassigned'}</strong></div><div class="wide"><span>Rental Period</span><strong>${fmtDate(r.start)} → ${fmtDate(r.end)}</strong></div><div><span>Balance</span><strong>${money(bal)}</strong></div><div class="customer-history-open">Open ›</div></button>`}).join('')}</div>`:'<div class="empty">No rental history recorded.</div>';
    openModal(customerDisplayName(c),`<div class="customer-compact-summary"><div class="customer-summary-block"><span class="customer-summary-label">Customer</span><strong>${esc(customerDisplayName(c))}</strong><div class="customer-summary-contact"><span>Phone</span><b>${esc(c.mobile||c.phone||'No mobile recorded')}</b>${c.secondary_phone?`<span>Secondary</span><b>${esc(c.secondary_phone)}</b>`:''}${c.email?`<span>Email</span><b>${esc(c.email)}</b>`:''}</div></div><div class="customer-summary-block account"><div><span>Rentals</span><strong>${rentals.length}</strong></div><div><span>Outstanding</span><strong>${money(outstanding)}</strong></div><div><span>Current Rental</span><strong>${active?`#${esc(active.id)}`:'None'}</strong></div></div></div><div class="customer-profile-actions">${active?'<button type="button" class="btn btn-primary" id="profileOpenRental">Open Current Rental</button>':''}<button type="button" class="btn btn-whatsapp" id="profileWhatsApp">WhatsApp</button></div><div class="detail-tabs-section customer-history-section"><h3>Rental History</h3>${history}</div>`,null,'Close');
    $('#modalForm').onsubmit=e=>{e.preventDefault();$('#modal').close();};
    $('#profileOpenRental')?.addEventListener('click',()=>{$('#modal').close();setTimeout(()=>openRentalNow(active.uuid),20);});
    $('#profileWhatsApp')?.addEventListener('click',()=>openWhatsAppForCustomer(c,defaultCustomerMessage(c,active)));
    $$('[data-customer-rental]').forEach(row=>row.onclick=()=>{$('#modal').close();setTimeout(()=>openRentalNow(row.dataset.customerRental),20);});
    const contracts=(state.contracts||[]).filter(ct=>rentals.some(r=>String(r.uuid)===String(ct.rental_agreement_id)));
    if(contracts.length){const sec=document.createElement('div');sec.className='detail-tabs-section customer-contract-section';sec.innerHTML=`<h3>Contracts (${contracts.length})</h3>${contracts.map(ct=>`<button type="button" class="contract-history-row" data-v086-contract="${esc(ct.rental_agreement_id)}"><strong>${esc(ct.contract_number)}</strong><span>${esc(ct.status)}</span><span>Open ›</span></button>`).join('')}`;$('#modalBody').appendChild(sec);$$('[data-v086-contract]').forEach(b=>b.onclick=()=>openContract(b.dataset.v086Contract));}
  };

  function promoBenefitLabel(p){if(p.benefit_type==='Percent Discount')return `${Number(p.discount_percent||0)}% off`;if(p.benefit_type==='Free Day')return `${Number(p.free_days||1)} free day${Number(p.free_days||1)===1?'':'s'}`;return p.notes||'Promotion';}
  function promoCustomerName(id){const c=state.customers.find(x=>String(x.id)===String(id));return c?customerDisplayName(c):'Any customer';}
  function promoManagerSection(){const rows=state.promoCodes||[];return `<div class="panel"><div class="panel-head"><div><h3>Promo Codes</h3><div class="vehicle-meta">Generate and review promotional offers.</div></div><button type="button" class="btn btn-primary btn-small" id="generatePromoCodeV086">Generate Code</button></div><div class="promo-history">${rows.length?rows.map(p=>`<div class="promo-history-row"><div><span class="promo-mini-label">Code</span><strong>${esc(p.code)}</strong></div><div><span class="promo-mini-label">Offer</span><strong>${esc(promoBenefitLabel(p))}</strong></div><div><span class="promo-mini-label">Customer</span><span>${esc(promoCustomerName(p.customer_id))}</span></div><div><span class="promo-mini-label">Status</span><span class="badge badge-demo">${esc(p.status||'Available')}</span></div><div><span class="promo-mini-label">Expires</span><small>${p.expires_at?fmtDate(p.expires_at):'No expiry'}</small></div></div>`).join(''):'<div class="empty">No promo codes generated yet.</div>'}</div></div>`;}

  const priorManagerDetail=renderManagerDetail;
  renderManagerDetail=function(view,testRates,users,logs){if(view==='promos')return promoManagerSection();return priorManagerDetail(view,testRates,users,logs);};

  function codeValue(){return 'B5-'+Math.random().toString(36).slice(2,7).toUpperCase();}
  function openPromoGeneratorV086(){
    const defaultUntil=new Date();defaultUntil.setDate(defaultUntil.getDate()+7);
    openModal('Generate Promo Code',`<div class="grid two-col"><div class="field"><label>Promo Code</label><input id="promoCode86" value="${codeValue()}"></div><div class="field"><label>Offer Type</label><select id="promoType86"><option value="Percent Discount">Percentage off</option><option value="Free Day">One free day</option></select></div><div class="field"><label>Value</label><select id="promoValue86"><option value="5">5%</option><option value="10" selected>10%</option><option value="15">15%</option><option value="20">20%</option></select></div><div class="field"><label>Customer (optional)</label><select id="promoCustomer86"><option value="">Any customer</option>${[...state.customers].sort((a,b)=>customerDisplayName(a).localeCompare(customerDisplayName(b))).map(c=>`<option value="${esc(c.id)}">${esc(customerDisplayName(c))}</option>`).join('')}</select></div><div class="field"><label>Valid From</label><input id="promoFrom86" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Valid Until</label><input id="promoUntil86" type="date" value="${defaultUntil.toISOString().slice(0,10)}"></div><div class="field" style="grid-column:1/-1"><label>Description / Reference</label><input id="promoNotes86" placeholder="e.g. Winter offer, loyalty reward"></div></div>`,async()=>{
      const code=$('#promoCode86').value.trim().toUpperCase(),type=$('#promoType86').value,value=Number($('#promoValue86').value||0);if(!code){alert('Enter a promo code.');return false;}
      if(type==='Percent Discount'&&![5,10,15,20].includes(value)){alert('Choose 5%, 10%, 15% or 20%.');return false;}
      const {data:{session}}=await window.db.auth.getSession();
      const payload={code,benefit_type:type,discount_percent:type==='Percent Discount'?value:null,free_days:type==='Free Day'?1:null,discount_amount:null,customer_id:$('#promoCustomer86').value||null,starts_at:$('#promoFrom86').value?new Date($('#promoFrom86').value+'T00:00:00').toISOString():null,expires_at:$('#promoUntil86').value?new Date($('#promoUntil86').value+'T23:59:59').toISOString():null,notes:$('#promoNotes86').value.trim()||null,status:'Available',created_by:session?.user?.id||null};
      const {error}=await window.db.from('promo_codes').insert(payload);if(error){alert(error.message);return false;}await loadSupabaseData();state.managerView='promos';render();return true;
    },'Create Promo Code');
    const typeEl=$('#promoType86'),valueEl=$('#promoValue86');
    const syncValue=()=>{if(typeEl.value==='Free Day'){valueEl.innerHTML='<option value="1">1 free day</option>';valueEl.disabled=true;}else{valueEl.disabled=false;valueEl.innerHTML='<option value="5">5%</option><option value="10" selected>10%</option><option value="15">15%</option><option value="20">20%</option>';}};
    typeEl?.addEventListener('change',syncValue);syncValue();
  }

  const priorBind=bindPageEvents;
  bindPageEvents=function(){priorBind();if(state.page==='manager'&&state.managerView==='promos'){const old=document.getElementById('generatePromoCodeV086');if(old)old.onclick=openPromoGeneratorV086;}};
})();