/* B5 v0.8.79 — expanded Settings centre */
(function(){
 const oldRenderSettings=renderSettings,oldBindPageEvents=bindPageEvents;
 const STORE='b5-user-settings-v1';
 const defaults={landing:'dashboard',density:'compact',theme:'system',dateFormat:'au',timeFormat:'12',timezone:'Asia/Beirut',currency:'USD',pickup:'',dropoff:'',guarantee:'Specific Vehicle',duration:'7',rememberPage:false};
 function read(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORE)||'{}')};}catch{return {...defaults};}}
 function write(v){localStorage.setItem(STORE,JSON.stringify(v));}
 function icon(k){return ({preferences:'⚙',notifications:'🔔',device:'▣',rental:'🚗',regional:'🌐',sync:'↻',about:'ⓘ'})[k]||'•';}
 function row(k,title,sub,trail='›'){return `<button type="button" class="settings-row" data-settings-open="${k}"><span class="settings-icon">${icon(k)}</span><span class="settings-row-copy"><strong>${title}</strong><small>${sub}</small></span><span class="settings-trail">${trail}</span></button>`;}
 function syncText(){return state.live?'Online · Live data connected':'Offline · Check connection';}
 renderSettings=function(){return `<div class="settings-centre"><div class="settings-list">${row('preferences','My Preferences','Default page, display density and workflow preferences')}${row('notifications','Notifications','Push alerts and reminder preferences')}${row('device','This Device','Notification permission, device registration and app installation')}${row('rental','Rental Defaults','Pickup, drop-off and booking defaults')}${row('regional','Regional','Currency, dates, time and timezone')}${row('sync','Data & Sync',syncText(),state.live?'<span class="settings-online">Online</span>':'<span class="settings-offline">Offline</span>')}${row('about','About B5',`Version ${versionInfo().version} · ${versionInfo().build||'Build information'}`)}</div></div>`;};
 function locationOpts(selected){return `<option value="">No default</option>`+(state.locations||[]).map(l=>`<option value="${esc(l.id)}" ${String(selected)===String(l.id)?'selected':''}>${esc(l.name)}</option>`).join('');}
 function openSheet(kind){const s=read(),title=document.getElementById('modalTitle'),body=document.getElementById('modalBody'),save=document.getElementById('modalSave'),cancel=document.getElementById('modalCancelBtn'),dlg=document.getElementById('modal');let html='',heading='Settings';
  if(kind==='preferences'){heading='My Preferences';html=`<div class="settings-form"><div class="field"><label>Default landing page</label><select id="setLanding"><option value="dashboard" ${s.landing==='dashboard'?'selected':''}>Dashboard</option><option value="today" ${s.landing==='today'?'selected':''}>Today</option><option value="rentals" ${s.landing==='rentals'?'selected':''}>Rentals</option><option value="availability" ${s.landing==='availability'?'selected':''}>Availability</option></select></div><div class="field"><label>Display density</label><select id="setDensity"><option value="compact" ${s.density==='compact'?'selected':''}>Compact</option><option value="comfortable" ${s.density==='comfortable'?'selected':''}>Comfortable</option></select></div><label class="settings-toggle-row"><span><strong>Remember last page</strong><small>Return to the last section used on this device.</small></span><input id="setRemember" type="checkbox" ${s.rememberPage?'checked':''}></label></div>`;}
  if(kind==='notifications'){heading='Notifications';html=`<div class="settings-explain"><strong>Push notification settings</strong><p>Manage pickup, return, overdue and maintenance alerts for this account and device.</p><button type="button" class="btn btn-primary" id="openNotificationProfile">Open Notification Settings</button></div>`;}
  if(kind==='device'){heading='This Device';const supported='Notification'in window&&'serviceWorker'in navigator;html=`<div class="settings-info-grid"><div><span>Device</span><strong>${esc(typeof deviceType==='function'?deviceType():(navigator.userAgentData?.platform||navigator.platform||'Device'))}</strong></div><div><span>Browser</span><strong>${esc(typeof browserName==='function'?browserName():navigator.userAgent.split(' ').slice(-1)[0])}</strong></div><div class="wide"><span>Device ID</span><strong>${esc(getDeviceId())}</strong></div><div class="wide"><span>Notification permission</span><strong>${supported?esc(Notification.permission):'Not supported'}</strong></div></div><div class="settings-explain"><p>B5 device-specific push controls are available under Notifications.</p></div>`;}
  if(kind==='rental'){heading='Rental Defaults';html=`<div class="settings-form"><div class="field"><label>Default pickup location</label><select id="setPickup">${locationOpts(s.pickup)}</select></div><div class="field"><label>Default drop-off location</label><select id="setDropoff">${locationOpts(s.dropoff)}</select></div><div class="field"><label>Default guarantee</label><select id="setGuarantee"><option ${s.guarantee==='Specific Vehicle'?'selected':''}>Specific Vehicle</option><option ${s.guarantee==='Vehicle or Similar'?'selected':''}>Vehicle or Similar</option></select></div><div class="field"><label>Default rental duration</label><select id="setDuration">${[1,3,7,14,30].map(n=>`<option value="${n}" ${String(s.duration)===String(n)?'selected':''}>${n} day${n===1?'':'s'}</option>`).join('')}</select></div></div>`;}
  if(kind==='regional'){heading='Regional';html=`<div class="settings-form"><div class="field"><label>Currency</label><select id="setCurrency"><option ${s.currency==='USD'?'selected':''}>USD</option><option ${s.currency==='LBP'?'selected':''}>LBP</option></select></div><div class="field"><label>Date format</label><select id="setDate"><option value="au" ${s.dateFormat==='au'?'selected':''}>DD/MM/YYYY</option><option value="iso" ${s.dateFormat==='iso'?'selected':''}>YYYY-MM-DD</option></select></div><div class="field"><label>Time format</label><select id="setTime"><option value="12" ${s.timeFormat==='12'?'selected':''}>12-hour</option><option value="24" ${s.timeFormat==='24'?'selected':''}>24-hour</option></select></div><div class="field"><label>Timezone</label><select id="setTimezone"><option value="Asia/Beirut" ${s.timezone==='Asia/Beirut'?'selected':''}>Lebanon — Beirut</option><option value="Australia/Sydney" ${s.timezone==='Australia/Sydney'?'selected':''}>Australia — Sydney</option></select></div></div><div class="settings-explain"><p>Regional preferences are stored now; full currency conversion is not applied automatically to existing financial records.</p></div>`;}
  if(kind==='sync'){heading='Data & Sync';html=`<div class="settings-sync-status ${state.live?'online':'offline'}"><span>${state.live?'●':'○'}</span><div><strong>${state.live?'Online':'Offline'}</strong><small>${state.live?'Connected to live B5 data':'Live data connection is unavailable'}</small></div></div><button type="button" class="btn btn-secondary" id="settingsRefreshData">Refresh Live Data</button><div class="settings-explain"><p>Refreshing reloads the latest vehicles, rentals, customers, locations and account data.</p></div>`;}
  if(kind==='about'){heading='About B5';const v=versionInfo();html=`<div class="settings-about"><div class="settings-b5-mark">B5</div><h3>All Season Car Rental</h3><p>Operations and rental management system</p></div><div class="settings-info-grid"><div><span>Version</span><strong>v${esc(v.version)}</strong></div><div><span>Build</span><strong>${esc(v.build||'')}</strong></div><div class="wide"><span>Released</span><strong>${esc(v.released||'')}</strong></div></div><button type="button" class="btn btn-secondary" id="settingsReleaseNotes">View Release Notes</button>`;}
  title.textContent=heading;body.innerHTML=html;save.textContent=['preferences','rental','regional'].includes(kind)?'Save':'Close';cancel.hidden=true;dlg.showModal();
  if(!['preferences','rental','regional'].includes(kind))save.onclick=()=>dlg.close();else save.onclick=null;
  if(kind==='notifications')document.getElementById('openNotificationProfile').onclick=()=>{dlg.close();if(typeof openUserProfile==='function')openUserProfile();setTimeout(()=>{if(typeof renderNotificationPanel==='function')renderNotificationPanel();},0);};
  if(kind==='sync')document.getElementById('settingsRefreshData').onclick=async()=>{await loadSupabaseData();dlg.close();};
  if(kind==='about')document.getElementById('settingsReleaseNotes').onclick=()=>{dlg.close();document.getElementById('versionBtn')?.click();};
  document.getElementById('modalForm').onsubmit=e=>{e.preventDefault();if(!['preferences','rental','regional'].includes(kind)){dlg.close();return;}const n=read();if(kind==='preferences'){n.landing=document.getElementById('setLanding').value;n.density=document.getElementById('setDensity').value;n.rememberPage=document.getElementById('setRemember').checked;}if(kind==='rental'){n.pickup=document.getElementById('setPickup').value;n.dropoff=document.getElementById('setDropoff').value;n.guarantee=document.getElementById('setGuarantee').value;n.duration=document.getElementById('setDuration').value;}if(kind==='regional'){n.currency=document.getElementById('setCurrency').value;n.dateFormat=document.getElementById('setDate').value;n.timeFormat=document.getElementById('setTime').value;n.timezone=document.getElementById('setTimezone').value;}write(n);apply(n);dlg.close();};
 }
 function apply(s=read()){document.documentElement.dataset.density=s.density||'compact';document.documentElement.dataset.theme=s.theme||'system';}
 window.B5UserSettings={read,apply};apply();
 bindPageEvents=function(){oldBindPageEvents();if(state.page==='settings')document.querySelectorAll('[data-settings-open]').forEach(b=>b.onclick=()=>openSheet(b.dataset.settingsOpen));};
})();