/* B5 v0.8.85 — overdue drill-down, availability cards, manager tools */
(function(){
  Object.assign(state,{promoCodes:state.promoCodes||[]});
  const oldLoad=loadSupabaseData, oldRenderManager=renderManager, oldRenderManagerDetail=renderManagerDetail, oldBind=bindPageEvents;
  loadSupabaseData=async function(){await oldLoad();if(state.live){const {data,error}=await window.db.from('promo_codes').select('*').order('created_at',{ascending:false});state.promoCodes=error?[]:(data||[]);}};

  const oldOverdue=overdueRentalTable;
  overdueRentalTable=function(rows){return oldOverdue(rows).replaceAll('<tr>','<tr class="clickable-row overdue-rental-row">').replace(/<tr class="clickable-row overdue-rental-row">([\s\S]*?)data-open-rental="([^"]+)"/g,(m,inside,id)=>`<tr class="clickable-row overdue-rental-row" data-overdue-rental="${id}">${inside}data-open-rental="${id}"`);};

  availabilityGroup=function(title,rows,start,end,pickup,dropoff){
    return `<div class="panel result-section"><div class="panel-head"><h3>${esc(title)}</h3><span class="badge badge-available">${rows.length}</span></div><div class="panel-body">${rows.length?`<div class="vehicle-grid">${rows.slice(0,24).map(v=>{const weekly=Number(v.rate||0)*7;return `<div class="vehicle-card availability-vehicle-card" data-availability-vehicle="${esc(v.id)}"><div class="kpi-row"><span class="badge ${v.source==='External'?'badge-external':'badge-available'}">${esc(v.source)}</span>${v.supplier?`<span class="badge badge-external">${esc(v.supplier)}</span>`:''}</div><h3 style="margin-top:10px">${esc(v.make)} ${esc(v.model)}</h3><div class="vehicle-meta">${esc(v.plate||'Plate not recorded')} · ${esc(v.category)} · ${esc(v.seats)} seats · ${esc(v.transmission)}</div><div class="vehicle-rate">${Number(v.rate)>0?`${money(v.rate)}/day`:'Rate not loaded'}</div><div class="vehicle-meta availability-weekly">${Number(v.rate)>0?`Indicative ${money(weekly)} weekly`:'Weekly rate required'}</div><div class="card-actions"><button class="btn btn-primary btn-small" data-book-vehicle="${esc(v.id)}" data-start="${esc(start)}" data-end="${esc(end)}" data-pickup="${esc(pickup)}" data-dropoff="${esc(dropoff)}">Book</button></div></div>`;}).join('')}</div>`:'<div class="empty">No matching vehicles.</div>'}</div></div>`;
  };

  testRateTable=function(rows){if(!rows.length)return '<div class="empty">No test rates remain.</div>';return `<div class="test-rate-compact-list">${rows.map(v=>`<button type="button" class="test-rate-compact" data-test-rate-vehicle="${esc(v.id)}"><span><strong>${esc(v.make)} ${esc(v.model)}</strong><small>${esc(v.plate||'No plate')}</small></span><strong>${money(v.rate)}/day</strong><b>›</b></button>`).join('')}</div>`;};

  function missingPhoneCustomers(){return state.customers.filter(c=>!String(c.mobile||c.phone||'').trim());}
  function promoLabel(p){if(p.promotion_type==='percent')return `${Number(p.value||0)}% off`;if(p.promotion_type==='free_day')return `${Number(p.value||1)} free day${Number(p.value||1)===1?'':'s'}`;if(p.promotion_type==='fixed_amount')return `${money(p.value)} off`;return p.description||'Promotion';}
  function customerName(id){const c=state.customers.find(x=>String(x.id)===String(id));return c?customerDisplayName(c):'Not assigned';}
  function promoSection(){const rows=state.promoCodes||[];return `<div class="panel"><div class="panel-head"><div><h3>Promo Codes</h3><div class="vehicle-meta">Generate and review promotional offers.</div></div><button type="button" class="btn btn-primary btn-small" id="generatePromoCode">Generate Code</button></div><div class="promo-history">${rows.length?rows.map(p=>`<div class="promo-history-row"><strong>${esc(p.code)}</strong><span>${esc(promoLabel(p))}</span><span>${esc(customerName(p.customer_id))}</span><span class="badge badge-demo">${esc(p.status)}</span><small>${p.created_at?fmtDate(p.created_at):''}</small></div>`).join(''):'<div class="empty">No promo codes generated yet.</div>'}</div></div>`;}
  function missingPhonesSection(){const rows=missingPhoneCustomers();return `<div class="panel"><div class="panel-head"><h3>Customers Without Telephone Numbers</h3><span class="badge badge-reserved">${rows.length}</span></div><div class="test-rate-compact-list">${rows.length?rows.map(c=>`<button type="button" class="test-rate-compact" data-missing-phone-customer="${esc(c.id)}"><span><strong>${esc(customerDisplayName(c))}</strong><small>${esc(c.email||'No email recorded')}</small></span><strong>Add phone</strong><b>›</b></button>`).join(''):'<div class="empty">Every customer has a telephone number.</div>'}</div></div>`;}

  renderManager=function(){let html=oldRenderManager();if(!isManager())return html;const missing=missingPhoneCustomers().length,promos=(state.promoCodes||[]).length;html=html.replace('</div>\n    <div class="manager-detail"',`<button class="manager-tile ${state.managerView==='missingphones'?'active':''}" data-manager-view="missingphones"><div class="manager-tile-label">Missing Phones</div><div class="manager-tile-value">${missing}</div><div class="manager-tile-sub">Customer records without telephone numbers</div></button><button class="manager-tile ${state.managerView==='promos'?'active':''}" data-manager-view="promos"><div class="manager-tile-label">Promo Codes</div><div class="manager-tile-value">${promos}</div><div class="manager-tile-sub">Generate codes and review promotion history</div></button></div>\n    <div class="manager-detail"`);return html;};
  renderManagerDetail=function(view,testRates,users,logs){if(view==='missingphones')return missingPhonesSection();if(view==='promos')return promoSection();return oldRenderManagerDetail(view,testRates,users,logs);};

  function makeCode(){return 'B5-'+Math.random().toString(36).slice(2,7).toUpperCase();}
  function openPromoGenerator(){openModal('Generate Promo Code',`<div class="grid two-col"><div class="field"><label>Promo Code</label><input id="promoCode" value="${makeCode()}"></div><div class="field"><label>Offer Type</label><select id="promoType"><option value="percent">Percentage off</option><option value="free_day">Free day</option><option value="fixed_amount">Fixed amount off</option><option value="other">Other</option></select></div><div class="field"><label>Value</label><input id="promoValue" type="number" min="0" step="0.01" value="10"></div><div class="field"><label>Customer (optional)</label><select id="promoCustomer"><option value="">Any customer</option>${[...state.customers].sort((a,b)=>customerDisplayName(a).localeCompare(customerDisplayName(b))).map(c=>`<option value="${esc(c.id)}">${esc(customerDisplayName(c))}</option>`).join('')}</select></div><div class="field"><label>Valid From</label><input id="promoFrom" type="date"></div><div class="field"><label>Valid Until</label><input id="promoUntil" type="date"></div><div class="field" style="grid-column:1/-1"><label>Description / Reference</label><input id="promoDescription" placeholder="e.g. Winter offer, loyalty reward"></div></div>`,async()=>{const code=$('#promoCode').value.trim().toUpperCase(),type=$('#promoType').value,value=Number($('#promoValue').value||0);if(!code)return false;const {data:{session}}=await window.db.auth.getSession();const payload={code,promotion_type:type,value:value||null,customer_id:$('#promoCustomer').value||null,valid_from:$('#promoFrom').value||null,valid_until:$('#promoUntil').value||null,description:$('#promoDescription').value.trim()||null,created_by:session?.user?.id||null};const {error}=await window.db.from('promo_codes').insert(payload);if(error){alert(error.message);return false;}await loadSupabaseData();state.managerView='promos';render();return true;},'Create Promo Code');}

  bindPageEvents=function(){oldBind();if(state.page==='manager'){document.getElementById('generatePromoCode')?.addEventListener('click',openPromoGenerator);document.querySelectorAll('[data-test-rate-vehicle]').forEach(b=>b.onclick=()=>openVehicleDetails(b.dataset.testRateVehicle));document.querySelectorAll('[data-missing-phone-customer]').forEach(b=>b.onclick=()=>openCustomerProfile(b.dataset.missingPhoneCustomer));}};

  document.addEventListener('click',e=>{const av=e.target.closest('[data-availability-vehicle]');if(av&&!e.target.closest('[data-book-vehicle]')){e.preventDefault();e.stopImmediatePropagation();openVehicleDetails(av.dataset.availabilityVehicle);}},true);
})();