/* B5 v0.8.93 — apply promo codes to new rental pricing */
(function(){
  const promoState={promo:null,amount:0,label:''};
  function now(){return new Date();}
  function promoByCode(code){const key=String(code||'').trim().toUpperCase();return (state.promoCodes||[]).find(p=>String(p.code||'').toUpperCase()===key)||null;}
  function promoLabel(p){if(!p)return'';if(p.benefit_type==='Percent Discount')return `${Number(p.discount_percent||0)}% off`;if(p.benefit_type==='Free Day')return `${Number(p.free_days||1)} free day`;return 'Promotion';}
  function validatePromo(p,customerId){if(!p)return 'Promo code not found.';if(String(p.status||'Available').toLowerCase()!=='available')return 'This promo code is no longer available.';const t=now();if(p.starts_at&&t<new Date(p.starts_at))return 'This promo code is not active yet.';if(p.expires_at&&t>new Date(p.expires_at))return 'This promo code has expired.';if(p.customer_id&&String(p.customer_id)!==String(customerId||''))return 'This promo code is assigned to a different customer.';return '';}
  function calculatePromo(p){const v=vehicleById($('#rVehicle')?.value),start=$('#rStart')?.value,end=$('#rEnd')?.value;if(!v||!start||!end||new Date(end)<=new Date(start))return 0;const rate=Number($('#rRate')?.value||v.rate||0),base=rentalDays(start,end)*rate;if(p.benefit_type==='Percent Discount')return Math.max(0,base*Number(p.discount_percent||0)/100);if(p.benefit_type==='Free Day')return Math.min(base,Math.max(0,Number(p.free_days||1))*rate);return 0;}
  function clearPromo(message=''){promoState.promo=null;promoState.amount=0;promoState.label='';const d=$('#rDiscount');if(d){d.readOnly=false;d.value='0';d.dispatchEvent(new Event('input',{bubbles:true}));}const s=$('#promoApplyStatus');if(s)s.innerHTML=message?`<div class="conflict-box">${esc(message)}</div>`:'';}
  function applyPromo(){const code=$('#rPromoCode')?.value||'',p=promoByCode(code),err=validatePromo(p,$('#rCustomer')?.value);if(err){clearPromo(err);return;}const amount=calculatePromo(p);if(amount<=0){clearPromo('Select the customer, vehicle and rental dates before applying the promo code.');return;}promoState.promo=p;promoState.amount=amount;promoState.label=promoLabel(p);const d=$('#rDiscount');if(d){d.value=amount.toFixed(2);d.readOnly=true;d.dispatchEvent(new Event('input',{bubbles:true}));}const s=$('#promoApplyStatus');if(s)s.innerHTML=`<div class="ok-box"><strong>${esc(p.code)}</strong> applied · ${esc(promoState.label)} · -${money(amount)}</div>`;}

  const oldBooking=bookingModal;
  bookingModal=function(prefill={}){promoState.promo=null;promoState.amount=0;promoState.label='';oldBooking(prefill);const discount=$('#rDiscount')?.closest('.field');if(!discount)return;discount.insertAdjacentHTML('beforebegin',`<div class="field promo-code-field"><label>Promo Code</label><div style="display:flex;gap:8px"><input id="rPromoCode" autocomplete="off" placeholder="e.g. B5-XXXXX" style="text-transform:uppercase"><button type="button" class="btn btn-secondary btn-small" id="rApplyPromo">Apply</button></div><div id="promoApplyStatus"></div></div>`);$('#rApplyPromo')?.addEventListener('click',applyPromo);$('#rPromoCode')?.addEventListener('input',()=>{if(promoState.promo)clearPromo();});['rCustomer','rVehicle','rStart','rEnd','rRate'].forEach(id=>$('#'+id)?.addEventListener('change',()=>{if(promoState.promo)applyPromo();}));};

  const oldSave=saveRentalAgreement;
  saveRentalAgreement=async function(){if(promoState.promo){const err=validatePromo(promoState.promo,$('#rCustomer')?.value);if(err){alert(err);return false;}const recalculated=calculatePromo(promoState.promo);if(Math.abs(recalculated-Number($('#rDiscount')?.value||0))>.01){$('#rDiscount').value=recalculated.toFixed(2);promoState.amount=recalculated;}}
    const before=new Set((state.rentals||[]).map(r=>String(r.uuid)));const promo=promoState.promo?{...promoState.promo}:null,amount=promoState.amount,label=promoState.label;const ok=await oldSave();if(ok!==true||!promo)return ok;
    try{const created=(state.rentals||[]).find(r=>!before.has(String(r.uuid)));const notes=[promo.notes,`Used on rental #${created?.id||created?.uuid||'new rental'} · ${label} · discount ${money(amount)}`].filter(Boolean).join(' | ');const {error}=await window.db.from('promo_codes').update({status:'Used',notes}).eq('id',promo.id);if(error)console.warn('Promo status update failed',error);await logAudit('promo_code_used','promo_code',promo.id,{code:promo.code,rental_agreement_id:created?.uuid||null,rental_number:created?.id||null,discount_amount:amount});const local=(state.promoCodes||[]).find(x=>String(x.id)===String(promo.id));if(local){local.status='Used';local.notes=notes;}}
    catch(e){console.warn('Promo completion update failed',e);}return ok;};
})();
