/* B5 v0.8.90 — notification deep-links, overdue opening + refined calendar */
(function(){
  function rentalByRef(ref){const key=String(ref||'').replace(/^#/,'').trim();return (state.rentals||[]).find(r=>String(r.uuid)===key||String(r.id)===key)||null;}
  function openRental(ref){const r=rentalByRef(ref);if(!r)return false;const id=r.uuid||r.id;if(typeof openRentalDetails==='function')openRentalDetails(id);else if(typeof openRentalInRentals==='function')openRentalInRentals(id);else if(typeof openRentalDirect==='function')openRentalDirect(id);return true;}
  function openVehicle(id){if(!id||(state.vehicles||[]).every(v=>String(v.id)!==String(id)))return false;if(typeof openVehicleDetails==='function')openVehicleDetails(id);return true;}
  function consumeDeepLink(){const hash=(location.hash||'').replace(/^#/,'');if(!hash)return true;let handled=false;if(hash.startsWith('rental='))handled=openRental(decodeURIComponent(hash.slice(7)));else if(hash.startsWith('rental-number='))handled=openRental(decodeURIComponent(hash.slice(14)));else if(hash.startsWith('vehicle='))handled=openVehicle(decodeURIComponent(hash.slice(8)));if(handled){history.replaceState(null,'',location.pathname+location.search+'#dashboard');return true;}return !/^(rental=|rental-number=|vehicle=)/.test(hash);}
  function waitForDeepLink(){let tries=0;const timer=setInterval(()=>{tries++;if(consumeDeepLink()||tries>120)clearInterval(timer);},500);}
  window.addEventListener('hashchange',waitForDeepLink);window.addEventListener('load',waitForDeepLink);setTimeout(waitForDeepLink,200);
  function rentalFromOverdueRow(row){const direct=row?.dataset?.overdueRental||row?.dataset?.openRental||row?.querySelector?.('[data-open-rental]')?.dataset?.openRental||'';if(direct){const r=rentalByRef(direct);return r?.uuid||r?.id||direct;}const m=(row?.textContent||'').match(/#\s*(\d+)/);if(!m)return '';const r=rentalByRef(m[1]);return r?.uuid||r?.id||'';}
  function decorateOverdueRows(root=document){root.querySelectorAll?.('.overdue-rental-row,[data-overdue-rental]').forEach(row=>{const id=rentalFromOverdueRow(row);if(id){row.dataset.overdueRental=id;row.classList.add('clickable-row');}});}
  const observer=new MutationObserver(muts=>muts.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)decorateOverdueRows(n.matches?.('.overdue-rental-row,[data-overdue-rental]')?(n.parentElement||document):n);})));window.addEventListener('load',()=>{decorateOverdueRows();observer.observe(document.body,{childList:true,subtree:true});});
  document.addEventListener('click',e=>{const row=e.target.closest?.('[data-overdue-rental],.overdue-rental-row');if(!row||e.target.closest('.overdue-actions'))return;const id=rentalFromOverdueRow(row);if(!id)return;e.preventDefault();e.stopImmediatePropagation();openRental(id);},true);

  if(state.calendarStatusFilter==null)state.calendarStatusFilter='out';
  function calendarDayStart(d){const x=new Date(d);x.setHours(0,0,0,0);return x;}
  function calendarDayEnd(d){const x=calendarDayStart(d);x.setDate(x.getDate()+1);return x;}
  function visibleSegments(vehicleId,days){const a=calendarDayStart(days[0]),b=calendarDayEnd(days[days.length-1]);return (state.segments||[]).filter(s=>String(s.vehicle_id)===String(vehicleId)&&s.start_at&&s.end_at&&overlaps(a,b,s.start_at,s.end_at));}
  function spanOf(seg,days){let first=-1,last=-1;days.forEach((d,i)=>{if(overlaps(calendarDayStart(d),calendarDayEnd(d),seg.start_at,seg.end_at)){if(first<0)first=i;last=i;}});return first<0?null:{first,last};}
  function calendarVehicles(){const f=state.calendarStatusFilter||'out';return (state.vehicles||[]).filter(v=>{const s=effectiveVehicleStatus(v);if(f==='all')return true;if(f==='out')return s==='Out on Rental';if(f==='reserved')return s==='Reserved';if(f==='available')return s==='Available';if(f==='review')return s==='Needs Review';if(f==='oos')return s==='Out of Order'||s==='Maintenance';return true;});}
  function rowRentalNumber(v,segs){const current=currentSegmentForVehicle(v.id);const seg=current||segs[0];const ag=seg?segmentAgreement(seg):null;return ag?.id?`#${ag.id}`:'';}
  function colourIndex(seed){let h=0;for(const ch of String(seed||''))h=(h*31+ch.charCodeAt(0))>>>0;return h%6;}

  renderCalendar=function(){
    const start=new Date();start.setHours(0,0,0,0);
    const days=Array.from({length:14},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});
    const vehicles=calendarVehicles();
    const fixedRows=vehicles.map(v=>{const segs=visibleSegments(v.id,days),rentalNo=rowRentalNumber(v,segs);return `<div class="calendar-fixed-row"><strong>${esc(v.make)} ${esc(v.model)}</strong><small>${esc(v.plate||'No plate')}${rentalNo?` &nbsp; (${esc(rentalNo)})`:''}</small></div>`;}).join('');
    const timelineRows=vehicles.map(v=>{const segs=visibleSegments(v.id,days);const bars=segs.map(seg=>{const span=spanOf(seg,days);if(!span)return'';const ag=segmentAgreement(seg),label=ag?.customer||'Booked',ref=ag?.uuid||ag?.id||seg.rental_agreement_id||'',ci=colourIndex(ref||label);return `<button type="button" class="calendar-span-bar colour-${ci}" style="grid-column:${span.first+1}/${span.last+2}" data-calendar-rental="${esc(ref)}" title="${esc(label)}">${esc(label)}</button>`;}).join('');return `<div class="calendar-scroll-row">${days.map(()=>'<div class="calendar-day-cell"></div>').join('')}${bars}</div>`;}).join('');
    return `<div class="calendar-filter-compact"><div><strong>Calendar Filter</strong><small>${vehicles.length} vehicles shown</small></div><label>Status <select id="calendarStatusFilter"><option value="out" ${state.calendarStatusFilter==='out'?'selected':''}>Out on Rental</option><option value="reserved" ${state.calendarStatusFilter==='reserved'?'selected':''}>Reserved</option><option value="available" ${state.calendarStatusFilter==='available'?'selected':''}>Available</option><option value="review" ${state.calendarStatusFilter==='review'?'selected':''}>Needs Review</option><option value="oos" ${state.calendarStatusFilter==='oos'?'selected':''}>Out of Order</option><option value="all" ${state.calendarStatusFilter==='all'?'selected':''}>All Vehicles</option></select></label></div><div class="panel"><div class="panel-head"><h3>Fleet Timeline — Next 14 Days</h3><div class="kpi-row"><span class="badge badge-out">Booked</span></div></div><div class="panel-body calendar-board-wrap"><div class="calendar-board"><div class="calendar-fixed"><div class="calendar-fixed-head">Vehicle</div>${fixedRows}</div><div class="calendar-scroll" id="calendarScroll"><div class="calendar-date-row">${days.map(d=>`<div>${d.toLocaleDateString('en-AU',{day:'2-digit',month:'short'})}</div>`).join('')}</div>${timelineRows}</div></div>${vehicles.length?'':'<div class="calendar-empty">No vehicles match this filter.</div>'}</div></div>`;
  };

  const oldBind=bindPageEvents;
  bindPageEvents=function(){oldBind();if(state.page==='calendar'){const f=document.getElementById('calendarStatusFilter');if(f)f.onchange=()=>{state.calendarStatusFilter=f.value;render();};document.querySelectorAll('[data-calendar-rental]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();openRental(b.dataset.calendarRental);});}};

  if(!document.getElementById('calendarV090Style')){const st=document.createElement('style');st.id='calendarV090Style';st.textContent=`
  .calendar-filter-compact{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 14px;margin-bottom:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel,#fff)}
  .calendar-filter-compact>div{display:flex;flex-direction:column}.calendar-filter-compact small{color:var(--muted);margin-top:2px}.calendar-filter-compact label{display:flex;align-items:center;gap:8px;font-size:12px;font-weight:800;color:var(--muted)}.calendar-filter-compact select{min-width:150px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;background:var(--panel,#fff);color:var(--ink)}
  .calendar-board-wrap{padding:0!important;overflow:hidden}.calendar-board{display:grid;grid-template-columns:168px minmax(0,1fr);width:100%;overflow:hidden;border-top:1px solid var(--line)}
  .calendar-fixed{position:relative;z-index:10;background:var(--panel,#fff);border-right:1px solid var(--line)}
  .calendar-fixed-head,.calendar-fixed-row{height:58px;box-sizing:border-box;padding:9px 12px;display:flex;flex-direction:column;justify-content:center;background:var(--panel,#fff);border-bottom:1px solid var(--line)}
  .calendar-fixed-head{height:44px;justify-content:flex-start;padding-top:11px;font-weight:800;color:var(--muted);text-align:left}
  .calendar-fixed-row strong{font-size:13px;line-height:1.15;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.calendar-fixed-row small{font-size:11px;color:var(--muted);margin-top:3px;white-space:nowrap}
  .calendar-scroll{overflow-x:auto;overflow-y:hidden;min-width:0;overscroll-behavior-x:contain}.calendar-date-row,.calendar-scroll-row{display:grid;grid-template-columns:repeat(14,124px);min-width:1736px;position:relative}
  .calendar-date-row{height:44px;position:sticky;top:0;z-index:6;background:var(--panel,#fff)}.calendar-date-row>div{height:44px;box-sizing:border-box;padding:8px 6px 0;text-align:center;font-size:12px;font-weight:800;color:var(--muted);border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:var(--panel,#fff)}
  .calendar-scroll-row{height:58px}.calendar-day-cell{height:58px;box-sizing:border-box;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}
  .calendar-span-bar{grid-row:1;align-self:center;z-index:4;height:30px;margin:0 5px;border-radius:9px;font-size:11px;font-weight:700;padding:0 10px;display:flex;align-items:center;justify-content:center;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;cursor:pointer;border:1px solid rgba(0,0,0,.12);box-shadow:0 1px 2px rgba(0,0,0,.06)}
  .calendar-span-bar.colour-0{background:#cfe8ff;color:#154c79;border-color:#8fc5ee}.calendar-span-bar.colour-1{background:#ffe0ad;color:#72460a;border-color:#efb95e}.calendar-span-bar.colour-2{background:#f6c5d3;color:#742a45;border-color:#df8faa}.calendar-span-bar.colour-3{background:#c7ead7;color:#17563a;border-color:#83c8a3}.calendar-span-bar.colour-4{background:#ddd0f5;color:#4b3475;border-color:#ad93df}.calendar-span-bar.colour-5{background:#c9e9eb;color:#15575d;border-color:#82c8cd}
  .calendar-empty{padding:28px;color:var(--muted)}
  [data-resolved-theme='dark'] .calendar-filter-compact,[data-resolved-theme='dark'] .calendar-fixed,[data-resolved-theme='dark'] .calendar-fixed-head,[data-resolved-theme='dark'] .calendar-fixed-row,[data-resolved-theme='dark'] .calendar-date-row,[data-resolved-theme='dark'] .calendar-date-row>div{background:#182438!important}
  @media(max-width:700px){.calendar-filter-compact{align-items:flex-end}.calendar-filter-compact label{flex-direction:column;align-items:flex-start;gap:4px}.calendar-filter-compact select{min-width:140px}.calendar-board{grid-template-columns:168px minmax(0,1fr)}.calendar-fixed-row strong{font-size:12px}}
  `;document.head.appendChild(st);}
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=0.8.90',{scope:'./'}).catch(console.warn));
})();