/* B5 v0.8.89 — notification deep-links, overdue opening + calendar refinement */
(function(){
  function rentalByRef(ref){const key=String(ref||'').replace(/^#/,'').trim();return (state.rentals||[]).find(r=>String(r.uuid)===key||String(r.id)===key)||null;}
  function openRental(ref){const r=rentalByRef(ref);if(!r)return false;const id=r.uuid||r.id;if(typeof openRentalDetails==='function')openRentalDetails(id);else if(typeof openRentalInRentals==='function')openRentalInRentals(id);else if(typeof openRentalDirect==='function')openRentalDirect(id);return true;}
  function openVehicle(id){if(!id||(state.vehicles||[]).every(v=>String(v.id)!==String(id)))return false;if(typeof openVehicleDetails==='function')openVehicleDetails(id);return true;}
  function consumeDeepLink(){const hash=(location.hash||'').replace(/^#/,'');if(!hash)return true;let handled=false;if(hash.startsWith('rental='))handled=openRental(decodeURIComponent(hash.slice(7)));else if(hash.startsWith('rental-number='))handled=openRental(decodeURIComponent(hash.slice(14)));else if(hash.startsWith('vehicle='))handled=openVehicle(decodeURIComponent(hash.slice(8)));if(handled){history.replaceState(null,'',location.pathname+location.search+'#dashboard');return true;}return !/^(rental=|rental-number=|vehicle=)/.test(hash);}
  function waitForDeepLink(){let tries=0;const timer=setInterval(()=>{tries++;if(consumeDeepLink()||tries>120)clearInterval(timer);},500);}
  window.addEventListener('hashchange',waitForDeepLink);window.addEventListener('load',waitForDeepLink);setTimeout(waitForDeepLink,200);
  function rentalFromOverdueRow(row){const direct=row?.dataset?.overdueRental||row?.dataset?.openRental||row?.querySelector?.('[data-open-rental]')?.dataset?.openRental||'';if(direct){const r=rentalByRef(direct);return r?.uuid||r?.id||direct;}const m=(row?.textContent||'').match(/#\s*(\d+)/);if(!m)return '';const r=rentalByRef(m[1]);return r?.uuid||r?.id||'';}
  function decorateOverdueRows(root=document){root.querySelectorAll?.('.overdue-rental-row,[data-overdue-rental]').forEach(row=>{const id=rentalFromOverdueRow(row);if(id){row.dataset.overdueRental=id;row.classList.add('clickable-row');}});}
  const observer=new MutationObserver(muts=>muts.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)decorateOverdueRows(n.matches?.('.overdue-rental-row,[data-overdue-rental]')?(n.parentElement||document):n);})));window.addEventListener('load',()=>{decorateOverdueRows();observer.observe(document.body,{childList:true,subtree:true});});
  document.addEventListener('click',e=>{const row=e.target.closest?.('[data-overdue-rental],.overdue-rental-row');if(!row||e.target.closest('.overdue-actions'))return;const id=rentalFromOverdueRow(row);if(!id)return;e.preventDefault();e.stopImmediatePropagation();openRental(id);},true);
  if(state.calendarStatusFilter==null)state.calendarStatusFilter='out';
  function calendarDayStart(d){const x=new Date(d);x.setHours(0,0,0,0);return x;}
  function calendarDayEnd(d){const x=calendarDayStart(d);x.setDate(x.getDate()+1);return x;}
  function visibleSegments(vehicleId,days){const a=calendarDayStart(days[0]),b=calendarDayEnd(days[days.length-1]);return (state.segments||[]).filter(s=>String(s.vehicle_id)===String(vehicleId)&&s.start_at&&s.end_at&&overlaps(a,b,s.start_at,s.end_at));}
  function spanOf(seg,days){let first=-1,last=-1;days.forEach((d,i)=>{if(overlaps(calendarDayStart(d),calendarDayEnd(d),seg.start_at,seg.end_at)){if(first<0)first=i;last=i;}});return first<0?null:{first,last};}
  function calendarVehicles(){const f=state.calendarStatusFilter||'out';return (state.vehicles||[]).filter(v=>{const s=effectiveVehicleStatus(v);if(f==='all')return true;if(f==='out')return s==='Out on Rental';if(f==='reserved')return s==='Reserved';if(f==='available')return s==='Available';if(f==='review')return s==='Needs Review';if(f==='oos')return s==='Out of Order'||s==='Maintenance';return true;});}
  function rowRentalNumber(v,segs){const current=currentSegmentForVehicle(v.id);const seg=current||segs[0];const ag=seg?segmentAgreement(seg):null;return ag?.id?`#${ag.id}`:'';}
  renderCalendar=function(){const start=new Date();start.setHours(0,0,0,0);const days=Array.from({length:14},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d;});const vehicles=calendarVehicles();return `<div class="calendar-filter-compact"><div><strong>Calendar Filter</strong><small>${vehicles.length} vehicles shown</small></div><label>Status <select id="calendarStatusFilter"><option value="out" ${state.calendarStatusFilter==='out'?'selected':''}>Out on Rental</option><option value="reserved" ${state.calendarStatusFilter==='reserved'?'selected':''}>Reserved</option><option value="available" ${state.calendarStatusFilter==='available'?'selected':''}>Available</option><option value="review" ${state.calendarStatusFilter==='review'?'selected':''}>Needs Review</option><option value="oos" ${state.calendarStatusFilter==='oos'?'selected':''}>Out of Order</option><option value="all" ${state.calendarStatusFilter==='all'?'selected':''}>All Vehicles</option></select></label></div><div class="panel"><div class="panel-head"><h3>Fleet Timeline — Next 14 Days</h3><div class="kpi-row"><span class="badge badge-out">Booked</span></div></div><div class="panel-body timeline"><div class="timeline-grid calendar-v089"><div class="timeline-row header"><div class="timeline-vehicle">Vehicle</div>${days.map(d=>`<div class="timeline-cell">${d.toLocaleDateString('en-AU',{day:'2-digit',month:'short'})}</div>`).join('')}</div>${vehicles.map(v=>{const segs=visibleSegments(v.id,days);const rentalNo=rowRentalNumber(v,segs);const bars=segs.map((seg,idx)=>{const span=spanOf(seg,days);if(!span)return'';const ag=segmentAgreement(seg),label=ag?.customer||'Booked',ref=ag?.uuid||ag?.id||seg.rental_agreement_id||'';return `<button type="button" class="calendar-span-bar colour-${idx%6}" style="grid-column:${span.first+2}/${span.last+3}" data-calendar-rental="${esc(ref)}" title="${esc(label)}">${esc(label)}</button>`;}).join('');return `<div class="timeline-row calendar-v089-row"><div class="timeline-vehicle"><strong>${esc(v.make)} ${esc(v.model)}</strong><small>${esc(v.plate||'No plate')}${rentalNo?` &nbsp; (${esc(rentalNo)})`:''}</small></div>${days.map(()=>'<div class="timeline-cell"></div>').join('')}${bars}</div>`;}).join('')}${vehicles.length?'':'<div class="calendar-empty">No vehicles match this filter.</div>'}</div></div></div>`;};
  const oldBind=bindPageEvents;bindPageEvents=function(){oldBind();if(state.page==='calendar'){const f=document.getElementById('calendarStatusFilter');if(f)f.onchange=()=>{state.calendarStatusFilter=f.value;render();};document.querySelectorAll('[data-calendar-rental]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();openRental(b.dataset.calendarRental);});}};
  if(!document.getElementById('calendarV089Style')){const st=document.createElement('style');st.id='calendarV089Style';st.textContent=`.calendar-filter-compact{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 14px;margin-bottom:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel,#fff)}.calendar-filter-compact>div{display:flex;flex-direction:column}.calendar-filter-compact small{color:var(--muted);margin-top:2px}.calendar-filter-compact label{display:flex;align-items:center;gap:8px;font-size:12px;font-weight:800;color:var(--muted)}.calendar-filter-compact select{min-width:150px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;background:var(--panel,#fff);color:var(--ink)}.calendar-v089-row{position:relative}.calendar-v089 .timeline-row>.timeline-vehicle{position:sticky!important;left:0!important;z-index:20!important;background:var(--panel,#fff)!important;box-shadow:6px 0 10px -10px rgba(20,35,55,.55)}.calendar-v089 .timeline-row.header>.timeline-vehicle{z-index:30!important;background:var(--panel,#fff)!important}.calendar-v089-row .timeline-vehicle{display:flex;flex-direction:column;gap:2px}.calendar-v089-row .timeline-vehicle small{font-weight:500;color:var(--muted);white-space:nowrap}.calendar-span-bar{grid-row:1;align-self:center;z-index:4;height:28px;margin:0 4px;border:1px solid rgba(18,105,63,.18);border-radius:9px;font-size:11px;padding:0 10px;display:flex;align-items:center;justify-content:center;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;cursor:pointer;background:#dff4e7;color:#174f32}.calendar-span-bar.colour-1{background:#d1eddb;color:#174b30}.calendar-span-bar.colour-2{background:#c0e5ce;color:#12472b}.calendar-span-bar.colour-3{background:#a9d9ba;color:#103f27}.calendar-span-bar.colour-4{background:#8fcca5;color:#0e3923}.calendar-span-bar.colour-5{background:#74bc90;color:#0a321e}.calendar-empty{padding:28px;color:var(--muted)}[data-resolved-theme='dark'] .calendar-filter-compact{background:#182438}[data-resolved-theme='dark'] .calendar-filter-compact select{background:#111c2e;color:#eef4fb}[data-resolved-theme='dark'] .calendar-v089 .timeline-row>.timeline-vehicle{background:#182438!important}[data-resolved-theme='dark'] .calendar-v089 .timeline-row.header>.timeline-vehicle{background:#182438!important}@media(max-width:700px){.calendar-filter-compact{align-items:flex-end}.calendar-filter-compact label{flex-direction:column;align-items:flex-start;gap:4px}.calendar-filter-compact select{min-width:140px}.timeline-grid.calendar-v089{min-width:1050px}.calendar-v089-row{min-height:58px}.calendar-v089-row .timeline-vehicle{font-size:11px}}`;document.head.appendChild(st);}
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=0.8.89',{scope:'./'}).catch(console.warn));
})();