/* v0.9.21 — Editable Action List + persistent navigation */
(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc2=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const originalRender=window.render;
  let actionItems=[];
  function manager(){ return window.state?.userProfile?.role==='manager' || (typeof isManager==='function' && isManager()); }
  function ensureNav(){const nav=$('#nav');if(!nav)return;let btn=$('#actionListNav');if(!btn){btn=document.createElement('button');btn.id='actionListNav';btn.className='nav-btn manager-only';btn.dataset.page='actionlist';btn.textContent='Action List';const managerBtn=$('#managerNav');nav.insertBefore(btn,managerBtn||null);btn.onclick=()=>{if(!manager())return;state.page='actionlist';render();document.body.classList.remove('sidebar-open');};}btn.hidden=!manager();}
  async function renderActionList(options={}){if(!manager()){state.page='dashboard';return originalRender();}const preserveScroll=options.preserveScroll===true,scrollY=preserveScroll?window.scrollY:0,focusId=options.focusId||null;const title=$('#pageTitle'),sub=$('#pageSubtitle'),content=$('#content');if(title)title.textContent='Action List';if(sub)sub.textContent='B5 client requirements and implementation checklist';$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page==='actionlist'));content.innerHTML='<div class="panel"><div class="panel-head"><div><h2>Client Requirements</h2><p>Manager-only working checklist. Status changes and edits are recorded in the audit log.</p></div></div><div id="actionListBody" class="action-list-loading">Loading…</div></div>';const {data,error}=await window.db.from('action_items').select('*').order('sort_order');const body=$('#actionListBody');if(!body)return;if(error){body.innerHTML='<div class="empty-state">Could not load the action list.</div>';return;}actionItems=data||[];const groups={};actionItems.forEach(x=>(groups[x.category]??=[]).push(x));const done=actionItems.filter(x=>x.completed).length,total=actionItems.length;body.innerHTML=`<div class="action-summary"><strong>${done} of ${total} completed</strong><span>${total?Math.round(done/total*100):0}%</span></div>`+Object.entries(groups).map(([cat,items])=>`<section class="action-category"><h3>${esc2(cat)}</h3>${items.map(i=>`<div class="action-item ${i.completed?'is-done':''}" data-item-row="${i.id}"><input type="checkbox" data-action-id="${i.id}" ${i.completed?'checked':''}><div class="action-copy"><strong>${esc2(i.title)}</strong>${i.notes?`<small>${esc2(i.notes)}</small>`:''}</div><button type="button" class="action-more" data-edit-id="${i.id}" aria-label="Edit ${esc2(i.title)}">⋮</button></div>`).join('')}</section>`).join('');body.querySelectorAll('[data-action-id]').forEach(cb=>cb.onchange=()=>toggleItem(cb));body.querySelectorAll('[data-edit-id]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();openEdit(btn.dataset.editId);});if(preserveScroll){requestAnimationFrame(()=>{window.scrollTo({top:scrollY,left:0,behavior:'instant'});const cb=focusId?body.querySelector(`[data-action-id="${focusId}"]`):null;if(cb)cb.focus({preventScroll:true});});}}
  async function toggleItem(cb){const id=cb.dataset.actionId,completed=cb.checked,item=actionItems.find(x=>String(x.id)===String(id)),title=item?.title||'Action item',scrollY=window.scrollY;cb.disabled=true;const {data:userData}=await window.db.auth.getUser();const uid=userData?.user?.id||null;const {error}=await window.db.from('action_items').update({completed,updated_at:new Date().toISOString(),updated_by:uid}).eq('id',id);if(error){cb.checked=!completed;cb.disabled=false;alert('Could not update this item.');return;}if(typeof window.logAudit==='function')await window.logAudit(completed?'action_item_completed':'action_item_reopened','action_item',id,{title,completed});await renderActionList({preserveScroll:true,focusId:id});requestAnimationFrame(()=>window.scrollTo({top:scrollY,left:0,behavior:'instant'}));}
  function openEdit(id){if(!manager())return;const item=actionItems.find(x=>String(x.id)===String(id));if(!item)return;const dlg=document.createElement('dialog');dlg.className='action-edit-dialog';dlg.innerHTML=`<form method="dialog" class="action-edit-card"><div class="modal-head"><div><h3>Edit Action Item</h3><div class="vehicle-meta">Update the requirement or add more detail.</div></div><button class="icon-btn" type="button" data-close aria-label="Close">✕</button></div><div class="field"><label>Title</label><input name="title" maxlength="160" value="${esc2(item.title)}" required></div><div class="field"><label>Description / Additional Notes</label><textarea name="notes" rows="7">${esc2(item.notes||'')}</textarea></div><div class="modal-actions"><button class="btn btn-secondary" type="button" data-cancel>Cancel</button><button class="btn btn-primary" type="submit">Save Changes</button></div></form>`;document.body.appendChild(dlg);const close=()=>{dlg.close();dlg.remove();};dlg.querySelector('[data-close]').onclick=close;dlg.querySelector('[data-cancel]').onclick=close;dlg.addEventListener('cancel',e=>{e.preventDefault();close();});dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,newTitle=form.title.value.trim(),newNotes=form.notes.value.trim();if(!newTitle)return;const save=form.querySelector('[type="submit"]');save.disabled=true;const {data:userData}=await window.db.auth.getUser();const uid=userData?.user?.id||null;const before={title:item.title,notes:item.notes||''};const {error}=await window.db.from('action_items').update({title:newTitle,notes:newNotes||null,updated_at:new Date().toISOString(),updated_by:uid}).eq('id',item.id);if(error){save.disabled=false;alert('Could not save this action item.');return;}if(typeof window.logAudit==='function')await window.logAudit('action_item_edited','action_item',item.id,{before,after:{title:newTitle,notes:newNotes}});const y=window.scrollY;close();await renderActionList({preserveScroll:true});requestAnimationFrame(()=>window.scrollTo({top:y,left:0,behavior:'instant'}));};dlg.showModal();}
  window.render=function(){ensureNav();if(state.page==='actionlist')return renderActionList();return originalRender.apply(this,arguments);};document.addEventListener('DOMContentLoaded',ensureNav);setTimeout(ensureNav,800);
})();

/* Global refresh-safe navigation. Current page/manager section is stored in the URL hash. */
(()=>{
  const pages=new Set(['dashboard','today','availability','rentals','calendar','fleet','customers','suppliers','locations','expenses','reports','settings','manager','actionlist']);
  const managerViews=new Set(['activity','users','promos','audit','discounts','monthly']);
  const parse=()=>{const raw=location.hash.replace(/^#\/?/,'');const [p='dashboard',s='']=raw.split('/').map(decodeURIComponent);return {page:pages.has(p)?p:'dashboard',section:s};};
  const startup=parse();let ready=false,applying=false;
  const hashForState=()=>{const section=state.page==='manager'&&state.managerView?`/${encodeURIComponent(state.managerView)}`:'';return `#/${encodeURIComponent(state.page||'dashboard')}${section}`;};
  const baseRender=window.render;
  window.render=function(){const out=baseRender.apply(this,arguments);if(ready&&!applying){const h=hashForState();if(location.hash!==h)history.pushState(null,'',h);}return out;};
  const baseStart=window.startB5App;
  window.startB5App=async function(){await baseStart.apply(this,arguments);ready=true;const restricted=(startup.page==='manager'||startup.page==='actionlist')&&!(typeof isManager==='function'&&isManager());applying=true;state.page=restricted?'dashboard':startup.page;if(state.page==='manager'&&managerViews.has(startup.section))state.managerView=startup.section;window.render();applying=false;history.replaceState(null,'',hashForState());};
  window.addEventListener('hashchange',()=>{if(!ready)return;const r=parse();const restricted=(r.page==='manager'||r.page==='actionlist')&&!(typeof isManager==='function'&&isManager());applying=true;state.page=restricted?'dashboard':r.page;if(state.page==='manager'&&managerViews.has(r.section))state.managerView=r.section;window.render();applying=false;});
})();