/* B5 v0.9.14 — customer search, GPS tracking, approvals, amendments, monthly accounts */
(function(){
  window.B5_V0914=true;
  Object.assign(state,{discountRequests:[],contractAmendments:[],monthlyReminderLog:[]});

  const oldNormalise=window.normaliseVehicle;
  if(typeof oldNormalise==='function') window.normaliseVehicle=function(row){const v=oldNormalise(row);v.gps_enabled=!!row.gps_enabled;return v;};
  const oldLoad=window.loadSupabaseData;
  if(typeof oldLoad==='function')window.loadSupabaseData=async function(){await oldLoad();if(!state.live)return;try{const [d,a,m]=await Promise.all([window.db.from('discount_requests').select('*').order('created_at',{ascending:false}),window.db.from('contract_amendments').select('*').order('created_at',{ascending:false}),window.db.from('monthly_reminder_log').select('*').order('created_at',{ascending:false})]);state.discountRequests=d.error?[]:(d.data||[]);state.contractAmendments=a.error?[]:(a.data||[]);state.monthlyReminderLog=m.error?[]:(m.data||[]);}catch(e){console.warn('v0.9.14 supplemental data',e);}render();};

  function customerText(c){return [c.first_name,c.family_name,c.full_name,c.mobile,c.secondary_phone,c.email,c.license_number,c.passport_number].filter(Boolean).join(' ').toLowerCase();}
  function enhanceCustomers(){
    if(state.page!=='customers')return;const content=document.getElementById('content');if(!content||document.getElementById('customerLiveSearch'))return;const host=content.querySelector('.section-title')||content.firstElementChild;if(!host)return;
    const box=document.createElement('div');box.className='b5-customer-search';box.innerHTML='<input id="customerLiveSearch" type="search" autocomplete="off" placeholder="Search customers by name, phone, email, licence or passport…"><div id="customerSearchMatches" class="b5-search-matches" hidden></div>';host.insertAdjacentElement('afterend',box);
    const input=box.querySelector('input'),matches=box.querySelector('#customerSearchMatches');input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(!q){matches.hidden=true;matches.innerHTML='';return;}const found=state.customers.filter(c=>customerText(c).includes(q)).slice(0,10);matches.innerHTML=found.map(c=>`<button type="button" data-customer-id="${esc(c.id)}"><strong>${esc(customerDisplayName(c))}${c.monthly_account?' <span class="monthly-account-badge">MONTHLY</span>':''}</strong><span>${esc(c.mobile||c.email||'')}</span></button>`).join('')||'<div class="b5-no-match">No matching customers</div>';matches.hidden=false;matches.querySelectorAll('[data-customer-id]').forEach(b=>b.onclick=()=>{input.value=customerDisplayName(customerById(b.dataset.customerId));matches.hidden=true;});});
  }
  function gpsDecorate(){if(state.page!=='fleet')return;document.querySelectorAll('[data-vehicle-details]').forEach(card=>{const v=vehicleById(card.dataset.vehicleDetails);if(v?.gps_enabled&&!card.querySelector('.gps-badge'))card.querySelector('.kpi-row')?.insertAdjacentHTML('beforeend','<span class="gps-badge" title="GPS tracker fitted">GPS</span>');});}
  function discountDecorate(){if(state.page!=='rentals')return;document.querySelectorAll('[data-rental-card]').forEach(card=>{const id=card.dataset.rentalCard,r=agreementByUuid(id);if(!r)return;const pending=state.discountRequests.find(x=>String(x.rental_agreement_id)===String(id)&&x.status==='pending'),approved=state.discountRequests.find(x=>String(x.rental_agreement_id)===String(id)&&x.status==='approved');if(card.querySelector('.adhoc-discount-actions'))return;const wrap=document.createElement('div');wrap.className='adhoc-discount-actions';if(!['Completed','Cancelled'].includes(r.status))wrap.innerHTML='<button type="button" class="btn btn-small btn-secondary">Request Discount</button>';if(pending&&isManager())wrap.innerHTML+=`<button type="button" class="btn btn-small btn-primary">Approve ${money(pending.discount_value)} Discount</button>`;if(approved)wrap.innerHTML+=`<span class="badge badge-available">Discount approved ${money(approved.discount_value)}</span>`;card.appendChild(wrap);const btns=wrap.querySelectorAll('button');if(btns[0]&&!pending)btns[0].onclick=e=>{e.stopPropagation();requestAdHocDiscount(id);};if(pending&&isManager()){const approve=[...btns].find(b=>b.textContent.includes('Approve'));if(approve)approve.onclick=e=>{e.stopPropagation();approveDiscountRequest(pending.id);};}});}
  const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{enhanceCustomers();gpsDecorate();discountDecorate();},0);return r;};

  const oldVehicleDetails=window.openVehicleDetails;if(typeof oldVehicleDetails==='function')window.openVehicleDetails=function(id){oldVehicleDetails(id);const v=vehicleById(id),body=document.getElementById('modalBody');if(!v||!body)return;const vehicleSection=body.querySelector('.rental-detail-section');if(vehicleSection&&!vehicleSection.querySelector('.gps-detail-control')){const control=document.createElement('div');control.className='gps-detail-control';control.innerHTML=`<label><input type="checkbox" id="vehicleGpsEnabled" ${v.gps_enabled?'checked':''}> GPS tracker fitted</label>`;vehicleSection.appendChild(control);control.querySelector('input').onchange=async e=>{const enabled=e.target.checked;const {error}=await window.db.from('vehicles').update({gps_enabled:enabled}).eq('id',id);if(error){e.target.checked=!enabled;return alert(error.message);}v.gps_enabled=enabled;};}};

  window.requestAdHocDiscount=async function(rentalId){const amount=prompt('Discount amount (USD)');if(amount===null)return;const value=Number(amount);if(!(value>0))return alert('Enter a valid discount amount.');const reason=prompt('Reason for discount')||'';const user=await currentAuthUser();const {error}=await window.db.from('discount_requests').insert({rental_agreement_id:rentalId,requested_by:user.id,discount_type:'amount',discount_value:value,reason});if(error)return alert(error.message);alert('Discount submitted for manager approval. It will not affect the rental total until approved.');await loadSupabaseData();};
  window.approveDiscountRequest=async function(id){if(!isManager())return alert('Manager approval required.');const {data:req,error:readErr}=await window.db.from('discount_requests').select('*').eq('id',id).single();if(readErr)return alert(readErr.message);if(req.status==='approved'){const p=state.staffProfiles.find(x=>x.user_id===req.approved_by);return alert(`This has been approved by ${p?.display_name||p?.email||'another manager'}.`);}const user=await currentAuthUser();const {data,error}=await window.db.rpc('approve_discount_request',{p_request_id:id});if(error)return alert(error.message);if(data?.already_approved){return alert(`This has already been approved by ${data.approved_by_name||'another manager'}.`);}alert('Discount approved and applied.');await loadSupabaseData();};
  window.addContractAmendment=async function(rentalId){if(!isManager())return alert('Only managers can add amendments to finalised contracts.');const description=prompt('Describe the contract amendment');if(!description)return;const raw=prompt('Financial adjustment in USD (optional; use a negative number for a credit)','0');const amount=raw===''?null:Number(raw),user=await currentAuthUser();const {error}=await window.db.from('contract_amendments').insert({rental_agreement_id:rentalId,description,amount:Number.isFinite(amount)?amount:null,created_by:user.id});if(error)return alert(error.message);alert('Amendment recorded. The original finalised contract was not changed.');};
  window.setMonthlyAccount=async function(customerId,enabled){if(!isManager())return alert('Manager access required.');const {error}=await window.db.from('customers').update({monthly_account:!!enabled,monthly_reminder_enabled:!!enabled}).eq('id',customerId);if(error)return alert(error.message);const c=customerById(customerId);if(c){c.monthly_account=!!enabled;c.monthly_reminder_enabled=!!enabled;}render();};
  window.sendMonthlyReminder=async function(customerId,outstanding){if(!isManager())return alert('Manager access required.');const c=customerById(customerId);if(!c?.email)return alert('This customer has no email address.');if(!confirm(`Email an outstanding-balance reminder to ${c.email}?\n\nOutstanding: ${money(outstanding)}`))return;const user=await currentAuthUser();await window.db.from('monthly_reminder_log').insert({customer_id:customerId,outstanding_balance:Number(outstanding||0),status:'sent',sent_by:user.id,sent_at:new Date().toISOString()});window.location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent('All Season Car Rental — Outstanding Balance Reminder')}&body=${encodeURIComponent(`Dear ${customerDisplayName(c)},\n\nThis is a reminder that your current outstanding balance with All Season Car Rental is ${money(outstanding)}.\n\nPlease contact us if you have any questions.\n\nAll Season Car Rental`)}`;};
})();