/* B5 v0.9.28 — Supplier completion + birthday customer messaging */
(()=>{
  state.supplierActivity=state.supplierActivity||[];
  const oldLoad=loadSupabaseData;
  loadSupabaseData=async function(){
    await oldLoad();if(!state.live)return;
    try{const {data,error}=await window.db.from('supplier_activity').select('*').order('activity_date',{ascending:false}).order('created_at',{ascending:false});state.supplierActivity=error?[]:(data||[]);}catch{state.supplierActivity=[];}
  };
  const typeOptions=['Vehicle Supplier','Tyres','Brakes','Parts','Products','Service / Repairs','Other'];
  const supplierActivities=id=>(state.supplierActivity||[]).filter(x=>String(x.supplier_id)===String(id));

  supplierEditModal=function(id=null){
    const s=id?state.suppliers.find(x=>String(x.id)===String(id)):null;
    openModal(s?'Edit Supplier':'Add Supplier',`<div class="grid two-col"><div class="field"><label>Supplier / Company Name</label><input id="supName" value="${esc(s?.name||'')}"></div><div class="field"><label>Supplier Type</label><select id="supType">${typeOptions.map(x=>`<option ${String(s?.supplier_type||'Vehicle Supplier')===x?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>Contact Person</label><input id="supContact" value="${esc(s?.contact_person||'')}"></div><div class="field"><label>Phone</label><input id="supPhone" value="${esc(s?.phone||'')}"></div><div class="field"><label>Email</label><input id="supEmail" value="${esc(s?.email||'')}"></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea id="supNotes">${esc(s?.notes||'')}</textarea></div></div>`,async()=>{
      const name=$('#supName').value.trim();if(!name){alert('Supplier name is required.');return false;}
      const p={name,supplier_type:$('#supType').value,contact_person:$('#supContact').value.trim()||null,phone:$('#supPhone').value.trim()||null,email:$('#supEmail').value.trim()||null,notes:$('#supNotes').value.trim()||null,active:true};
      const result=s?await window.db.from('suppliers').update(p).eq('id',s.id):await window.db.from('suppliers').insert(p);if(result.error){alert(result.error.message);return false;}await logAudit(s?'supplier_updated':'supplier_created','supplier',s?.id||null,{name,type:p.supplier_type});await loadSupabaseData();return true;
    },s?'Save Changes':'Add Supplier');
  };

  async function deleteSupplier(s){
    if(!isManager())return alert('Manager access required.');
    const vehicles=supplierVehicles(s.id),activity=supplierActivities(s.id);if(vehicles.length||activity.length)return alert('This supplier has linked vehicles or history and cannot be deleted. Deactivate it instead so the historical relationship is retained.');
    if(!confirm(`Permanently delete ${s.name}?`))return;
    const {error}=await window.db.from('suppliers').delete().eq('id',s.id);if(error)return alert(error.message);await logAudit('supplier_deleted','supplier',s.id,{name:s.name});$('#modal').close();await loadSupabaseData();
  }
  function addSupplierActivity(s){
    openModal(`Add Supplier History — ${s.name}`,`<div class="grid two-col"><div class="field"><label>Date</label><input id="saDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Type</label><select id="saType"><option>Product</option><option>Service</option><option>Parts</option><option>Tyres</option><option>Brakes</option><option>Vehicle</option><option>Other</option></select></div><div class="field" style="grid-column:1/-1"><label>Product / Service Description</label><input id="saDescription"></div><div class="field"><label>Amount</label><input id="saAmount" type="number" step="0.01" min="0"></div><div class="field"><label>Vehicle (optional)</label><select id="saVehicle"><option value="">None</option>${state.vehicles.map(v=>`<option value="${esc(v.id)}">${esc(v.make)} ${esc(v.model)} · ${esc(v.plate||'')}</option>`).join('')}</select></div><div class="field"><label>Reference</label><input id="saReference"></div><div class="field" style="grid-column:1/-1"><label>Notes</label><textarea id="saNotes"></textarea></div></div>`,async()=>{
      const description=$('#saDescription').value.trim();if(!description){alert('Description is required.');return false;}
      const payload={supplier_id:s.id,activity_date:$('#saDate').value,activity_type:$('#saType').value,description,amount:$('#saAmount').value===''?null:Number($('#saAmount').value),vehicle_id:$('#saVehicle').value||null,reference:$('#saReference').value.trim()||null,notes:$('#saNotes').value.trim()||null};
      const {error}=await window.db.from('supplier_activity').insert(payload);if(error){alert(error.message);return false;}await logAudit('supplier_activity_added','supplier',s.id,{description,type:payload.activity_type});await loadSupabaseData();return true;
    },'Add History');
  }
  openSupplierDetails=function(id){
    const s=state.suppliers.find(x=>String(x.id)===String(id));if(!s)return;const vehicles=supplierVehicles(s.id),history=supplierActivities(s.id);
    openModal(s.name,`<div class="customer-profile-grid"><div class="rental-detail-section"><h4>Supplier Details</h4><strong>${esc(s.name)}</strong><div class="vehicle-meta">${esc(s.supplier_type||'Vehicle Supplier')}</div>${s.contact_person?`<div class="vehicle-meta">Contact: ${esc(s.contact_person)}</div>`:''}<div class="vehicle-meta">${esc(s.phone||'No phone recorded')}</div>${s.email?`<div class="vehicle-meta">${esc(s.email)}</div>`:''}<div><span class="badge ${s.active===false?'badge-oos':'badge-available'}">${s.active===false?'Inactive':'Active'}</span></div></div><div class="rental-detail-section"><h4>Relationship</h4><div>Vehicles supplied: <strong>${vehicles.length}</strong></div><div>Products / services recorded: <strong>${history.length}</strong></div></div></div><div class="customer-profile-actions"><button type="button" class="btn btn-primary" id="supplierEdit">Edit Supplier</button><button type="button" class="btn btn-secondary" id="supplierAddHistory">Add Product / Service</button><button type="button" class="btn btn-secondary" id="supplierToggle">${s.active===false?'Reactivate':'Deactivate'}</button>${isManager()?'<button type="button" class="btn btn-secondary" id="supplierDelete">Delete</button>':''}</div><div class="detail-tabs-section"><h3>Cars Supplied (${vehicles.length})</h3>${vehicles.length?`<div class="vehicle-grid supplier-vehicle-grid">${vehicles.map(v=>`<button type="button" class="vehicle-card vehicle-drill-card" data-supplier-vehicle="${esc(v.id)}"><strong>${esc(v.make)} ${esc(v.model)}</strong><div class="vehicle-meta">${esc(v.plate||'No plate')} · ${esc(effectiveVehicleStatus(v))}</div></button>`).join('')}</div>`:'<div class="empty">No vehicles linked.</div>'}</div><div class="detail-tabs-section"><h3>Products / Services History (${history.length})</h3>${history.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Vehicle</th><th>Amount</th><th>Reference</th></tr></thead><tbody>${history.map(x=>{const v=x.vehicle_id?vehicleById(x.vehicle_id):null;return `<tr><td>${esc(x.activity_date||'')}</td><td>${esc(x.activity_type||'')}</td><td><strong>${esc(x.description||'')}</strong>${x.notes?`<div class="vehicle-meta">${esc(x.notes)}</div>`:''}</td><td>${v?`${esc(v.make)} ${esc(v.model)} · ${esc(v.plate||'')}`:'—'}</td><td>${x.amount==null?'—':money(x.amount)}</td><td>${esc(x.reference||'—')}</td></tr>`;}).join('')}</tbody></table></div>`:'<div class="empty">No products or services recorded yet.</div>'}</div>`,null,'Close');
    $('#modalForm').onsubmit=e=>{e.preventDefault();$('#modal').close();};$('#supplierEdit').onclick=()=>{$('#modal').close();setTimeout(()=>supplierEditModal(s.id),50);};$('#supplierAddHistory').onclick=()=>{$('#modal').close();setTimeout(()=>addSupplierActivity(s),50);};$('#supplierToggle').onclick=async()=>{const next=s.active===false;if(!next&&!confirm(`Deactivate ${s.name}? Historical vehicles and activity will remain linked.`))return;const{error}=await window.db.from('suppliers').update({active:next}).eq('id',s.id);if(error)return alert(error.message);$('#modal').close();await loadSupabaseData();};$('#supplierDelete')?.addEventListener('click',()=>deleteSupplier(s));$$('[data-supplier-vehicle]').forEach(b=>b.onclick=()=>{$('#modal').close();setTimeout(()=>openVehicleDetails(b.dataset.supplierVehicle),50);});
  };
  renderSuppliers=function(){const rows=[...state.suppliers].filter(s=>state.supplierShowInactive||s.active!==false).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')));return `<div class="section-title"><div><h2>Suppliers / Partner Companies</h2><p>Vehicle, parts, product and service suppliers with retained history</p></div><button class="btn btn-primary" id="newSupplierBtn">Add Supplier</button></div><div class="supplier-toolbar"><label><input type="checkbox" id="showInactiveSuppliers" ${state.supplierShowInactive?'checked':''}> Show inactive suppliers</label></div><div class="vehicle-grid">${rows.map(s=>`<button type="button" class="vehicle-card supplier-drill-card" data-supplier-details="${esc(s.id)}"><div class="kpi-row"><span class="badge ${s.active===false?'badge-oos':'badge-available'}">${s.active===false?'Inactive':'Active'}</span><span class="badge badge-demo">${esc(s.supplier_type||'Vehicle Supplier')}</span></div><h3>${esc(s.name)}</h3><div class="vehicle-meta">${esc(s.contact_person||'')}${s.contact_person&&s.phone?' · ':''}${esc(s.phone||'')}</div><div class="vehicle-rate">${supplierVehicles(s.id).length}</div><div class="vehicle-meta">cars · ${supplierActivities(s.id).length} history entries</div><div class="vehicle-drill-hint">View supplier details ›</div></button>`).join('')}</div>`;};

  function birthdayText(c){return `Happy Birthday ${c.first_name||customerDisplayName(c)}! 🎉 Wishing you a wonderful day from everyone at All Season Car Rental.`;}
  function appendBirthdayPreference(id){
    const c=customerById(id),body=$('#modalBody');if(!c||!body||body.querySelector('#birthdayMessagePreference'))return;const hasDob=!!c.date_of_birth;
    const box=document.createElement('div');box.id='birthdayMessagePreference';box.className='detail-tabs-section';box.innerHTML=`<h3>Birthday Message</h3><label class="b5-switch-line" style="opacity:${hasDob?'1':'.55'}"><input id="birthdayMessageEnabled" type="checkbox" ${c.birthday_message_enabled?'checked':''} ${hasDob?'':'disabled'}> Send / prepare Happy Birthday message</label><div class="vehicle-meta">${hasDob?`Birthday on file: ${esc(String(c.date_of_birth))}. B5 can prepare a WhatsApp birthday message for staff to send.`:'Add a date of birth to the customer profile before birthday messages can be enabled.'}</div>${hasDob&&c.birthday_message_enabled?'<button type="button" class="btn btn-secondary btn-small" id="birthdayPreview" style="margin-top:10px">Prepare Birthday Message</button>':''}`;body.appendChild(box);
    $('#birthdayMessageEnabled')?.addEventListener('change',async e=>{if(e.target.checked&&!c.date_of_birth){e.target.checked=false;return alert('A date of birth is required first.');}const {error}=await window.db.from('customers').update({birthday_message_enabled:e.target.checked}).eq('id',id);if(error){e.target.checked=!e.target.checked;return alert(error.message);}c.birthday_message_enabled=e.target.checked;});
    $('#birthdayPreview')?.addEventListener('click',()=>{if(typeof openWhatsAppForCustomer==='function')openWhatsAppForCustomer(c,birthdayText(c));});
  }
  const oldProfile=openCustomerProfile;openCustomerProfile=function(id){oldProfile(id);appendBirthdayPreference(id);};
  if(typeof window.openCustomerAccount==='function'){const oldAccount=window.openCustomerAccount;window.openCustomerAccount=function(id){oldAccount(id);appendBirthdayPreference(id);};}
})();